import { settingsGroups } from '../features/settings-center/settingsCenterModel';
import { SettingsAiPanel } from './SettingsAiPanel';
import { SettingsAppearancePanel } from './SettingsAppearancePanel';
import { SettingsChapterPanel } from './SettingsChapterPanel';
import { SettingsGeneralPanel } from './SettingsGeneralPanel';
import { SettingsReaderPanel } from './SettingsReaderPanel';
import { SettingsTranslationPanel } from './SettingsTranslationPanel';
import { MoyuReaderSettingsPanel } from '../features/reader-core/MoyuReaderSettingsPanel';
import {
  SettingsAccessibilityPanel,
  SettingsAnnotationPanel,
  SettingsDataPanel,
  SettingsDiagnosticsPanel,
  SettingsLibraryPanel,
  SettingsSearchPanel,
  SettingsShortcutPanel,
  SettingsTasksPanel,
  type SettingsSupplementalPanelsProps,
} from './SettingsSupplementalPanels';

export type SettingsPageGroupRendererProps = Record<string, any> & {
  settingsPageState: Record<string, any>;
  supplementalPanelProps: SettingsSupplementalPanelsProps;
};

export function renderSettingsGroup(group: typeof settingsGroups[number], props: SettingsPageGroupRendererProps) {
  const {
    settingsPageState,
    supplementalPanelProps,
    locale,
    localePreference,
    setLocalePreference,
    t,
    currentBookId,
    currentBookTitle,
    onOpenCurrentBookSettings,
    onApplyPresetToCurrentBook,
    privacyAiApiKeyFallbackPath,
    fontRenderingDiagnostics,
    localeOptions,
    startupPageOptions,
    startupOverviewModeOptions,
    readerPresetOptions,
    readerThemeOptions,
    readerLayoutOptions,
    readerPageModeOptions,
    readerPageVerticalAlignOptions,
    readerLongParagraphStrategyOptions,
    readerCjkPunctuationOptions,
    readerMixedTextSpacingOptions,
    readerFontWeightBoostOptions,
    readerAlignOptions,
    readerTitleNumberCleanupOptions,
    readerTitleDecorationOptions,
    readerInfoSlotOptions,
    readerHeaderFooterTimeFormatOptions,
    readerHeaderFooterProgressFormatOptions,
    readerAnimationOptions,
    multiWindowConflictStrategyOptions,
    readerProgressModeOptions,
    tocRuleChangeRebuildModeOptions,
    paragraphModeOptions,
    bookTitleBracketModeOptions,
    appThemeOptions,
    pageTitleModeOptions,
    topbarButtonOptions,
    navItemOptions,
    aiModelOptions,
    aiModels,
    aiProviderProfiles,
    activeAiProviderProfile,
    aiProviderProfileOptions,
    aiProviderKindOptions,
    aiEndpointOptions,
    aiCancelStrategyOptions,
    aiReasoningEffortOptions,
    aiResponseFormatOptions,
    aiModeOptions,
    availableAiModeOptions,
    aiScopeOptions,
    aiCommandScopeOptions,
    aiNoSelectionFallbackScopeOptions,
    aiScopePriorityStrategyOptions,
    aiRetrievalStrategyOptions,
    aiRetrievalQueryRewriteModeOptions,
    aiMultiStageRetrievalModeOptions,
    aiFtsUnavailableBehaviorOptions,
    aiDefaultOutputFormatOptions,
    aiCitationCardDefaultDensityOptions,
    aiCitationFieldStrictnessOptions,
    aiToolCallDisplayModeOptions,
    aiCitationDefaultSaveTargetOptions,
    customSlashCommandTemplateLibrary,
    cloudRedactionPreview,
    buildSettingsJsonPreview,
    confirmSettingsImportPreview,
    copyChapterParseDiagnostics,
    copyCurrentAiConfigAsProvider,
    copyDiagnosticSettingsSnapshot,
    exportSettingsSnapshot,
    importSettingsSnapshot,
    restoreAllSettingsDefaults,
    restoreReaderGlobalDefaults,
    undoLastSettingsChangeFromHistory,
    formatSettingsChangeTime,
    updateExtendedSetting,
    updateReaderGlobalSetting,
    updateTopbarButtonVisibility,
    updateVisibleNavItem,
    moveVisibleNavItem,
    restoreDefaultNavOrder,
    applyReaderGlobalPreset,
    saveCurrentReaderSettingsAsPreset,
    exportReaderCustomPresetsFromSettings,
    importReaderCustomPresetsFromSettings,
    applyReaderCustomPreset,
    applyReaderCustomPresetToCurrentBook,
    renameReaderCustomPresetFromSettings,
    deleteReaderCustomPresetFromSettings,
    updateReaderFontStack,
    parseReaderFontFallbackInput,
    exportReaderDiagnosticsFromSettings,
    updateChapterRule,
    updateTocTitleGroupRule,
    moveTocTitleGroupRule,
    removeTocTitleGroupRule,
    addTocTitleGroupRule,
    updateChapterRegexRule,
    moveChapterRegexRule,
    removeChapterRegexRule,
    addChapterRegexRule,
    exportCustomCleanupRulesFromSettings,
    importCustomCleanupRulesFromSettings,
    updateCustomCleanupRule,
    moveCustomCleanupRule,
    removeCustomCleanupRule,
    addCustomCleanupRule,
    refreshAiApiKeyStorageStatus,
    runAiConnectionTest,
    loadAiModels,
    selectAiProviderProfile,
    applyAiProviderProfile,
    createAiProviderProfile,
    deleteAiProviderProfile,
    updateAiProviderProfile,
    addAiProviderModels,
    selectAiProviderModel,
    updateAiProviderModelSettings,
    removeAiProviderModel,
    resetAiProviderModels,
    updateAppSettings,
    updateTranslationApiKey,
    clearCurrentBookCloudAiHistorySettingsData,
    clearAllCloudAiHistorySettingsData,
    exportCurrentBookCloudAiHistoryDiagnostics,
    exportAllCloudAiHistoryDiagnostics,
    updateCloudAiEnabledSetting,
    updateLocalAiEnabledSetting,
    updateDefaultAiModeSetting,
    updateAiCommandDefaultScope,
    updateAiBuiltInSlashCommandEnabled,
    updateAiCommandRetrievalStrategy,
    refreshCustomSlashCommandList,
    createCustomSlashCommandFromSettings,
    addCustomSlashCommandTemplate,
    startEditingCustomSlashCommand,
    saveCustomSlashCommandEdit,
    cancelCustomSlashCommandEdit,
    deleteCustomSlashCommandFromSettings,
    exportCustomSlashCommandsFromSettings,
    importCustomSlashCommandsFromSettings,
    allowCurrentBookCloudAiSettingsData,
    revokeCurrentBookCloudAiConsentSettingsData,
  } = props;
  const {
    settings,
    extendedSettings,
    saveStatus,
    readerGlobalSettings,
    readerCustomPresets,
    readerPresetImportInputRef,
    chapterRules,
    chapterRegexTestInput,
    setChapterRegexTestInput,
    compactSplitPreviewInput,
    setCompactSplitPreviewInput,
    txtCleanupPreviewInput,
    setTxtCleanupPreviewInput,
    chapterDiagnosticsSampleInput,
    setChapterDiagnosticsSampleInput,
    customCleanupRuleImportInputRef,
    settingsImportInputRef,
    showSettingsJsonPreview,
    setShowSettingsJsonPreview,
    settingsImportPreview,
    setSettingsImportPreview,
    settingsChangeHistory,
    aiApiKeyStorageStatus,
    loadingAiApiKeyStorageStatus,
    aiApiKeyStorageStatusError,
    showApiKey,
    setShowApiKey,
    aiTestStatus,
    loadingAiModels,
    testingAi,
    cloudRedactionPreviewInput,
    setCloudRedactionPreviewInput,
    customSlashCommandList,
    customSlashCommandDraft,
    setCustomSlashCommandDraft,
    customSlashCommandEditingId,
    customSlashCommandEditDraft,
    setCustomSlashCommandEditDraft,
    customSlashCommandImportInputRef,
    highlightedSetting,
    aiApiSettingRef,
    readerMemoryWarningSettingRef,
  } = settingsPageState;

  if (group.id === 'general') return (
    <SettingsGeneralPanel
      locale={locale}
      localePreference={localePreference}
      setLocalePreference={setLocalePreference}
      t={t}
      localeOptions={localeOptions}
      extendedSettings={extendedSettings}
      startupPageOptions={startupPageOptions}
      startupOverviewModeOptions={startupOverviewModeOptions}
      updateExtendedSetting={updateExtendedSetting}
      saveStatus={saveStatus}
      restoreReaderGlobalDefaults={restoreReaderGlobalDefaults}
      settingsImportInputRef={settingsImportInputRef}
      exportSettingsSnapshot={exportSettingsSnapshot}
      importSettingsSnapshot={importSettingsSnapshot}
      showSettingsJsonPreview={showSettingsJsonPreview}
      setShowSettingsJsonPreview={setShowSettingsJsonPreview}
      buildSettingsJsonPreview={buildSettingsJsonPreview}
      copyDiagnosticSettingsSnapshot={copyDiagnosticSettingsSnapshot}
      settingsImportPreview={settingsImportPreview}
      confirmSettingsImportPreview={confirmSettingsImportPreview}
      setSettingsImportPreview={setSettingsImportPreview}
      settingsChangeHistory={settingsChangeHistory}
      undoLastSettingsChangeFromHistory={undoLastSettingsChangeFromHistory}
      formatSettingsChangeTime={formatSettingsChangeTime}
      restoreAllSettingsDefaults={restoreAllSettingsDefaults}
      searchText={t('settings.groupSearch.general')}
    />
  );
  if (group.id === 'appearance') return (
    <SettingsAppearancePanel
      t={t}
      readerGlobalSettings={readerGlobalSettings}
      readerThemeOptions={readerThemeOptions}
      updateReaderGlobalSetting={updateReaderGlobalSetting}
      extendedSettings={extendedSettings}
      appThemeOptions={appThemeOptions}
      pageTitleModeOptions={pageTitleModeOptions}
      topbarButtonOptions={topbarButtonOptions}
      navItemOptions={navItemOptions}
      updateExtendedSetting={updateExtendedSetting}
      updateTopbarButtonVisibility={updateTopbarButtonVisibility}
      updateVisibleNavItem={updateVisibleNavItem}
      moveVisibleNavItem={moveVisibleNavItem}
      restoreDefaultNavOrder={restoreDefaultNavOrder}
      searchText={t('settings.groupSearch.appearance')}
    />
  );
  if (group.id === 'reader') return (
    <SettingsReaderPanel
      t={t}
      currentBookTitle={currentBookTitle}
      onOpenCurrentBookSettings={onOpenCurrentBookSettings}
      onApplyPresetToCurrentBook={onApplyPresetToCurrentBook}
      readerGlobalSettings={readerGlobalSettings}
      readerCustomPresets={readerCustomPresets}
      readerPresetImportInputRef={readerPresetImportInputRef}
      readerPresetOptions={readerPresetOptions}
      readerThemeOptions={readerThemeOptions}
      readerLayoutOptions={readerLayoutOptions}
      readerPageModeOptions={readerPageModeOptions}
      readerPageVerticalAlignOptions={readerPageVerticalAlignOptions}
      readerLongParagraphStrategyOptions={readerLongParagraphStrategyOptions}
      readerCjkPunctuationOptions={readerCjkPunctuationOptions}
      readerMixedTextSpacingOptions={readerMixedTextSpacingOptions}
      readerFontWeightBoostOptions={readerFontWeightBoostOptions}
      readerAlignOptions={readerAlignOptions}
      readerTitleNumberCleanupOptions={readerTitleNumberCleanupOptions}
      readerTitleDecorationOptions={readerTitleDecorationOptions}
      readerInfoSlotOptions={readerInfoSlotOptions}
      readerHeaderFooterTimeFormatOptions={readerHeaderFooterTimeFormatOptions}
      readerHeaderFooterProgressFormatOptions={readerHeaderFooterProgressFormatOptions}
      readerAnimationOptions={readerAnimationOptions}
      multiWindowConflictStrategyOptions={multiWindowConflictStrategyOptions}
      readerProgressModeOptions={readerProgressModeOptions}
      fontRenderingDiagnostics={fontRenderingDiagnostics}
      extendedSettings={extendedSettings}
      applyReaderGlobalPreset={applyReaderGlobalPreset}
      saveCurrentReaderSettingsAsPreset={saveCurrentReaderSettingsAsPreset}
      exportReaderCustomPresetsFromSettings={exportReaderCustomPresetsFromSettings}
      importReaderCustomPresetsFromSettings={importReaderCustomPresetsFromSettings}
      formatSettingsChangeTime={formatSettingsChangeTime}
      applyReaderCustomPreset={applyReaderCustomPreset}
      applyReaderCustomPresetToCurrentBook={applyReaderCustomPresetToCurrentBook}
      renameReaderCustomPresetFromSettings={renameReaderCustomPresetFromSettings}
      deleteReaderCustomPresetFromSettings={deleteReaderCustomPresetFromSettings}
      updateReaderGlobalSetting={updateReaderGlobalSetting}
      updateReaderFontStack={updateReaderFontStack}
      parseReaderFontFallbackInput={parseReaderFontFallbackInput}
      updateExtendedSetting={updateExtendedSetting}
      exportReaderDiagnosticsFromSettings={exportReaderDiagnosticsFromSettings}
      copyChapterParseDiagnostics={copyChapterParseDiagnostics}
      highlightedSetting={highlightedSetting}
      readerMemoryWarningSettingRef={readerMemoryWarningSettingRef}
      searchText={t('settings.groupSearch.reader')}
    />
  );
  if (group.id === 'moyu') return (
    <MoyuReaderSettingsPanel
      profile={extendedSettings.moyuReaderProfile}
      onChange={(profile) => updateExtendedSetting('moyuReaderProfile', profile)}
    />
  );
  if (group.id === 'chapters') return (
    <SettingsChapterPanel
      t={t}
      chapterRules={chapterRules}
      extendedSettings={extendedSettings}
      tocRuleChangeRebuildModeOptions={tocRuleChangeRebuildModeOptions}
      paragraphModeOptions={paragraphModeOptions}
      bookTitleBracketModeOptions={bookTitleBracketModeOptions}
      chapterRegexTestInput={chapterRegexTestInput}
      setChapterRegexTestInput={setChapterRegexTestInput}
      compactSplitPreviewInput={compactSplitPreviewInput}
      setCompactSplitPreviewInput={setCompactSplitPreviewInput}
      txtCleanupPreviewInput={txtCleanupPreviewInput}
      setTxtCleanupPreviewInput={setTxtCleanupPreviewInput}
      txtCleanupPreviewOutput={props.txtCleanupPreviewOutput}
      chapterDiagnosticsSampleInput={chapterDiagnosticsSampleInput}
      setChapterDiagnosticsSampleInput={setChapterDiagnosticsSampleInput}
      chapterDiagnosticsCleanedContent={props.chapterDiagnosticsCleanedContent}
      chapterParseDiagnostics={props.chapterParseDiagnostics}
      customCleanupRuleImportInputRef={customCleanupRuleImportInputRef}
      updateExtendedSetting={updateExtendedSetting}
      updateChapterRule={updateChapterRule}
      updateTocTitleGroupRule={updateTocTitleGroupRule}
      moveTocTitleGroupRule={moveTocTitleGroupRule}
      removeTocTitleGroupRule={removeTocTitleGroupRule}
      addTocTitleGroupRule={addTocTitleGroupRule}
      updateChapterRegexRule={updateChapterRegexRule}
      moveChapterRegexRule={moveChapterRegexRule}
      removeChapterRegexRule={removeChapterRegexRule}
      addChapterRegexRule={addChapterRegexRule}
      exportCustomCleanupRulesFromSettings={exportCustomCleanupRulesFromSettings}
      importCustomCleanupRulesFromSettings={importCustomCleanupRulesFromSettings}
      updateCustomCleanupRule={updateCustomCleanupRule}
      moveCustomCleanupRule={moveCustomCleanupRule}
      removeCustomCleanupRule={removeCustomCleanupRule}
      addCustomCleanupRule={addCustomCleanupRule}
      copyChapterParseDiagnostics={copyChapterParseDiagnostics}
      searchText={t('settings.groupSearch.chapters')}
    />
  );
  if (group.id === 'library') return <SettingsLibraryPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.library')} />;
  if (group.id === 'ai') return (
    <SettingsAiPanel
      t={t}
      settings={settings}
      extendedSettings={extendedSettings}
      currentBookId={currentBookId}
      currentBookTitle={currentBookTitle}
      highlightedSetting={highlightedSetting}
      aiApiSettingRef={aiApiSettingRef}
      showApiKey={showApiKey}
      setShowApiKey={setShowApiKey}
      aiApiKeyStorageStatus={aiApiKeyStorageStatus}
      loadingAiApiKeyStorageStatus={loadingAiApiKeyStorageStatus}
      aiApiKeyStorageStatusError={aiApiKeyStorageStatusError}
      privacyAiApiKeyFallbackPath={privacyAiApiKeyFallbackPath}
      refreshAiApiKeyStorageStatus={refreshAiApiKeyStorageStatus}
      aiTestStatus={aiTestStatus}
      testingAi={testingAi}
      loadingAiModels={loadingAiModels}
      aiModelOptions={aiModelOptions}
      aiModels={aiModels}
      loadAiModels={loadAiModels}
      runAiConnectionTest={runAiConnectionTest}
      aiProviderProfiles={aiProviderProfiles}
      activeAiProviderProfile={activeAiProviderProfile}
      aiProviderProfileOptions={aiProviderProfileOptions}
      aiProviderKindOptions={aiProviderKindOptions}
      aiEndpointOptions={aiEndpointOptions}
      aiCancelStrategyOptions={aiCancelStrategyOptions}
      aiReasoningEffortOptions={aiReasoningEffortOptions}
      aiResponseFormatOptions={aiResponseFormatOptions}
      selectAiProviderProfile={selectAiProviderProfile}
      applyAiProviderProfile={applyAiProviderProfile}
      createAiProviderProfile={createAiProviderProfile}
      copyCurrentAiConfigAsProvider={copyCurrentAiConfigAsProvider}
      deleteAiProviderProfile={deleteAiProviderProfile}
      updateAiProviderProfile={updateAiProviderProfile}
      addAiProviderModels={addAiProviderModels}
      selectAiProviderModel={selectAiProviderModel}
      updateAiProviderModelSettings={updateAiProviderModelSettings}
      removeAiProviderModel={removeAiProviderModel}
      resetAiProviderModels={resetAiProviderModels}
      updateAppSettings={updateAppSettings}
      updateExtendedSetting={updateExtendedSetting}
      clearCurrentBookCloudAiHistorySettingsData={clearCurrentBookCloudAiHistorySettingsData}
      clearAllCloudAiHistorySettingsData={clearAllCloudAiHistorySettingsData}
      exportCurrentBookCloudAiHistoryDiagnostics={exportCurrentBookCloudAiHistoryDiagnostics}
      exportAllCloudAiHistoryDiagnostics={exportAllCloudAiHistoryDiagnostics}
      updateCloudAiEnabledSetting={updateCloudAiEnabledSetting}
      updateLocalAiEnabledSetting={updateLocalAiEnabledSetting}
      aiModeOptions={aiModeOptions}
      availableAiModeOptions={availableAiModeOptions}
      aiScopeOptions={aiScopeOptions}
      aiCommandScopeOptions={aiCommandScopeOptions}
      aiNoSelectionFallbackScopeOptions={aiNoSelectionFallbackScopeOptions}
      aiScopePriorityStrategyOptions={aiScopePriorityStrategyOptions}
      aiRetrievalStrategyOptions={aiRetrievalStrategyOptions}
      aiRetrievalQueryRewriteModeOptions={aiRetrievalQueryRewriteModeOptions}
      aiMultiStageRetrievalModeOptions={aiMultiStageRetrievalModeOptions}
      aiFtsUnavailableBehaviorOptions={aiFtsUnavailableBehaviorOptions}
      aiDefaultOutputFormatOptions={aiDefaultOutputFormatOptions}
      aiCitationCardDefaultDensityOptions={aiCitationCardDefaultDensityOptions}
      aiCitationFieldStrictnessOptions={aiCitationFieldStrictnessOptions}
      aiToolCallDisplayModeOptions={aiToolCallDisplayModeOptions}
      aiCitationDefaultSaveTargetOptions={aiCitationDefaultSaveTargetOptions}
      updateDefaultAiModeSetting={updateDefaultAiModeSetting}
      updateAiCommandDefaultScope={updateAiCommandDefaultScope}
      updateAiBuiltInSlashCommandEnabled={updateAiBuiltInSlashCommandEnabled}
      updateAiCommandRetrievalStrategy={updateAiCommandRetrievalStrategy}
      customSlashCommandList={customSlashCommandList}
      customSlashCommandDraft={customSlashCommandDraft}
      setCustomSlashCommandDraft={setCustomSlashCommandDraft}
      customSlashCommandEditingId={customSlashCommandEditingId}
      customSlashCommandEditDraft={customSlashCommandEditDraft}
      setCustomSlashCommandEditDraft={setCustomSlashCommandEditDraft}
      customSlashCommandImportInputRef={customSlashCommandImportInputRef}
      customSlashCommandTemplateLibrary={customSlashCommandTemplateLibrary}
      refreshCustomSlashCommandList={refreshCustomSlashCommandList}
      createCustomSlashCommandFromSettings={createCustomSlashCommandFromSettings}
      addCustomSlashCommandTemplate={addCustomSlashCommandTemplate}
      startEditingCustomSlashCommand={startEditingCustomSlashCommand}
      saveCustomSlashCommandEdit={saveCustomSlashCommandEdit}
      cancelCustomSlashCommandEdit={cancelCustomSlashCommandEdit}
      deleteCustomSlashCommandFromSettings={deleteCustomSlashCommandFromSettings}
      exportCustomSlashCommandsFromSettings={exportCustomSlashCommandsFromSettings}
      importCustomSlashCommandsFromSettings={importCustomSlashCommandsFromSettings}
      cloudRedactionPreview={cloudRedactionPreview}
      cloudRedactionPreviewInput={cloudRedactionPreviewInput}
      setCloudRedactionPreviewInput={setCloudRedactionPreviewInput}
      allowCurrentBookCloudAiSettingsData={allowCurrentBookCloudAiSettingsData}
      revokeCurrentBookCloudAiConsentSettingsData={revokeCurrentBookCloudAiConsentSettingsData}
    />
  );
  if (group.id === 'translation') return (
    <SettingsTranslationPanel
      t={t}
      settings={settings}
      aiProviderProfiles={aiProviderProfiles}
      updateAppSettings={updateAppSettings}
      updateTranslationApiKey={updateTranslationApiKey}
    />
  );
  if (group.id === 'search') return <SettingsSearchPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.search')} />;
  if (group.id === 'annotations') return <SettingsAnnotationPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.annotations')} />;
  if (group.id === 'data') return <SettingsDataPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.data')} />;
  if (group.id === 'tasks') return <SettingsTasksPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.tasks')} />;
  if (group.id === 'shortcuts') return <SettingsShortcutPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.shortcuts')} />;
  if (group.id === 'accessibility') return <SettingsAccessibilityPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.accessibility')} />;
  return <SettingsDiagnosticsPanel {...supplementalPanelProps} searchText={t('settings.groupSearch.diagnostics')} />;
}
