import type { Dispatch, SetStateAction } from 'react';
import type { LocalePreference, Translator } from '../i18n';
import type { DataBackupResult } from '../services/dataBackupService';
import type { OperationLogLevel } from '../types';
import type { AppSettings, ReaderSettings } from '../types';
import type { DataDirectoryMigrationProgress, DataDirectoryStatus, ExtendedSettings, LocalEncryptionStatus } from '../services/settingsCenterService';
import type { EncryptionCoverageItem, SettingsScopeItem } from '../features/settings-center/settingsCenterModel';
import type { SettingsPerformanceTuningProfile } from '../features/settings-center/settingsCenterPerformanceModel';

type SelectOption<T extends string> = {
  value: T;
  label: string;
};

type OperationLogEntry = {
  at: string;
  level: Exclude<OperationLogLevel, 'none'>;
  action: string;
  detail?: Record<string, unknown>;
};


export type SettingsSupplementalPanelsProps = {
  searchText?: string;
  t: Translator;
  locale: string;
  localePreference: LocalePreference;
  setLocalePreference: (preference: LocalePreference) => void;
  settings: AppSettings;
  extendedSettings: ExtendedSettings;
  readerGlobalSettings: ReaderSettings;
  currentBookId: string;
  currentBookTitle?: string;
  diagnosticPaths: { dataDir: string; settingsFile: string; ftsDatabase: string };
  privacyDiagnosticPaths: { dataDir: string; settingsFile: string; ftsDatabase: string };
  localEncryptionStatus: LocalEncryptionStatus | null;
  loadingLocalEncryptionStatus: boolean;
  localEncryptionStatusError: string;
  privacyLocalEncryptionFallbackPath: string;
  masterPasswordDraft: string;
  setMasterPasswordDraft: Dispatch<SetStateAction<string>>;
  masterPasswordVerifyDraft: string;
  setMasterPasswordVerifyDraft: Dispatch<SetStateAction<string>>;
  masterPasswordBusy: boolean;
  localKeyRotationBusy: boolean;
  lastLocalKeyRotationSummary: string;
  dataDirectoryStatus: DataDirectoryStatus | null;
  dataDirectoryBusy: boolean;
  dataDirectoryError: string;
  dataDirectoryMigrationProgress: DataDirectoryMigrationProgress | null;
  selectedDataBackupPath: string;
  dataBackupBusy: boolean;
  lastDataBackupResult: DataBackupResult | null;
  diagnosticsRedactionPreview: string;
  setDiagnosticsRedactionPreview: Dispatch<SetStateAction<string>>;
  operationLogs: OperationLogEntry[];
  filteredOperationLogs: OperationLogEntry[];
  operationLogFilterLevel: 'all' | Exclude<OperationLogLevel, 'none'>;
  setOperationLogFilterLevel: Dispatch<SetStateAction<'all' | Exclude<OperationLogLevel, 'none'>>>;
  operationLogFilterQuery: string;
  setOperationLogFilterQuery: Dispatch<SetStateAction<string>>;
  setOperationLogs: Dispatch<SetStateAction<OperationLogEntry[]>>;
  performanceTuningProfile: SettingsPerformanceTuningProfile;
  shortcutConflictMessages: string[];
  localeOptions: SelectOption<LocalePreference>[];
  translationFallbackOptions: SelectOption<ExtendedSettings['translationFallbackStrategy']>[];
  retentionSelectOptions: SelectOption<string>[];
  libraryViewOptions: SelectOption<ExtendedSettings['defaultViewMode']>[];
  librarySortOptions: SelectOption<ExtendedSettings['defaultSort']>[];
  libraryFilterOptions: SelectOption<ExtendedSettings['defaultFilter']>[];
  duplicateStrategyOptions: SelectOption<ExtendedSettings['duplicateStrategy']>[];
  defaultCoverToneStrategyOptions: SelectOption<ExtendedSettings['defaultCoverToneStrategy']>[];
  defaultCoverLabelStrategyOptions: SelectOption<ExtendedSettings['defaultCoverLabelStrategy']>[];
  importFileFilterOptions: SelectOption<ExtendedSettings['importFileFilter']>[];
  txtImportEncodingModeOptions: SelectOption<ExtendedSettings['txtImportEncodingMode']>[];
  libraryDensityOptions: SelectOption<ExtendedSettings['libraryDensity']>[];
  searchScopeOptions: SelectOption<ExtendedSettings['searchScope']>[];
  globalSearchModeOptions: SelectOption<ExtendedSettings['globalSearchMode']>[];
  readerSearchChapterFilterOptions: SelectOption<ExtendedSettings['readerSearchChapterFilterDefault']>[];
  readerSearchHighlightColorOptions: SelectOption<ExtendedSettings['readerSearchHighlightColor']>[];
  indexStrategyVersionOptions: SelectOption<ExtendedSettings['indexStrategyVersion']>[];
  ftsRepairStrategyOptions: SelectOption<ExtendedSettings['ftsRepairStrategy']>[];
  indexRebuildStrategyOptions: SelectOption<ExtendedSettings['indexRebuildStrategy']>[];
  indexPauseResumeStrategyOptions: SelectOption<ExtendedSettings['indexPauseResumeStrategy']>[];
  highlightColorOptions: SelectOption<ExtendedSettings['defaultHighlightColor']>[];
  highlightColorShortcutOptions: SelectOption<ExtendedSettings['highlightColorShortcuts'][ExtendedSettings['defaultHighlightColor']]>[];
  highlightImportanceOptions: SelectOption<ExtendedSettings['defaultHighlightImportance']>[];
  highlightReviewStatusOptions: SelectOption<ExtendedSettings['defaultHighlightReviewStatus']>[];
  highlightOverlapStrategyOptions: SelectOption<ExtendedSettings['highlightOverlapStrategy']>[];
  anchorRepairStrategyOptions: SelectOption<ExtendedSettings['anchorRepairStrategy']>[];
  exportFormatOptions: SelectOption<ExtendedSettings['defaultExportFormat']>[];
  annotationExportContentOptions: SelectOption<ExtendedSettings['annotationExportContent']>[];
  annotationJsonImportConflictStrategyOptions: SelectOption<ExtendedSettings['annotationJsonImportConflictStrategy']>[];
  noteDefaultSaveTargetOptions: SelectOption<ExtendedSettings['noteDefaultSaveTarget']>[];
  annotationCsvFieldOptions: SelectOption<ExtendedSettings['annotationCsvFields'][number]>[];
  knowledgeDefaultColumnOptions: SelectOption<ExtendedSettings['knowledgeDefaultColumns'][number]>[];
  bookmarkSortOptions: SelectOption<ExtendedSettings['defaultBookmarkSort']>[];
  bookmarkGroupOptions: SelectOption<ExtendedSettings['defaultBookmarkGroupBy']>[];
  dataAutoBackupFrequencyOptions: SelectOption<ExtendedSettings['dataAutoBackupFrequency']>[];
  dataBackupModeOptions: SelectOption<ExtendedSettings['dataBackupMode']>[];
  backgroundTaskNotificationModeOptions: SelectOption<ExtendedSettings['backgroundTaskNotificationMode']>[];
  taskCenterDefaultStatusFilterOptions: SelectOption<ExtendedSettings['taskCenterDefaultStatusFilter']>[];
  commandPaletteShortcutOptions: SelectOption<ExtendedSettings['commandPaletteShortcut']>[];
  commandPaletteSortModeOptions: SelectOption<ExtendedSettings['commandPaletteSortMode']>[];
  readerNavigationShortcutOptions: SelectOption<ExtendedSettings['navigationShortcuts']['reader']>[];
  libraryNavigationShortcutOptions: SelectOption<ExtendedSettings['navigationShortcuts']['library']>[];
  searchNavigationShortcutOptions: SelectOption<ExtendedSettings['navigationShortcuts']['search']>[];
  importShortcutOptions: SelectOption<ExtendedSettings['importShortcut']>[];
  aiSummaryShortcutOptions: SelectOption<ExtendedSettings['aiSummaryShortcut']>[];
  readerHighlightShortcutOptions: SelectOption<ExtendedSettings['readerShortcuts']['highlight']>[];
  readerBookmarkShortcutOptions: SelectOption<ExtendedSettings['readerShortcuts']['bookmark']>[];
  readerAiPanelShortcutOptions: SelectOption<ExtendedSettings['readerShortcuts']['aiPanel']>[];
  readerSearchShortcutOptions: SelectOption<ExtendedSettings['readerShortcuts']['search']>[];
  operationLogOptions: SelectOption<OperationLogLevel>[];
  operationLogFilterLevelOptions: SelectOption<'all' | Exclude<OperationLogLevel, 'none'>>[];
  taskLogRetentionOptions: SelectOption<ExtendedSettings['taskLogRetention']>[];
  settingsScopeMatrix: SettingsScopeItem[];
  encryptionCoverageMatrix: EncryptionCoverageItem[];
  updateAppSettings: (update: Partial<AppSettings>, status?: string) => Promise<void> | void;
  updateExtendedSetting: <K extends keyof ExtendedSettings>(key: K, value: ExtendedSettings[K]) => void;
  updateReaderGlobalSetting: <K extends keyof ReaderSettings>(key: K, value: ReaderSettings[K]) => void;
  useAppDataDirAsDefaultImportPath: () => Promise<void> | void;
  toggleAnnotationCsvField: (field: ExtendedSettings['annotationCsvFields'][number], enabled: boolean) => void;
  toggleKnowledgeDefaultColumn: (column: ExtendedSettings['knowledgeDefaultColumns'][number], enabled: boolean) => void;
  updateHighlightColorMeaning: (color: ExtendedSettings['defaultHighlightColor'], value: string) => void;
  updateHighlightColorShortcut: (color: ExtendedSettings['defaultHighlightColor'], value: ExtendedSettings['highlightColorShortcuts'][ExtendedSettings['defaultHighlightColor']]) => void;
  chooseAndMigrateDataDirectoryFromSettings: () => Promise<void> | void;
  enablePortableDataDirectoryFromSettings: () => Promise<void> | void;
  openDataDirectoryFromSettings: () => Promise<void> | void;
  getDataDirectoryStatusFromSettings: () => Promise<DataDirectoryStatus | null> | void;
  refreshLocalEncryptionStatus: () => Promise<void> | void;
  setMasterPasswordFromSettings: () => Promise<void> | void;
  verifyMasterPasswordFromSettings: () => Promise<void> | void;
  rotateLocalDataKeyFromSettings: () => Promise<void> | void;
  chooseDataBackupDirectoryFromSettings: () => Promise<void> | void;
  createDataBackupFromSettings: () => Promise<void> | void;
  restoreDataBackupFromSettings: () => Promise<void> | void;
  clearCurrentBookAllDataSettingsData: () => Promise<void> | void;
  clearAllReaderCacheSettingsData: () => Promise<void> | void;
  clearCurrentBookReaderCacheSettingsData: () => Promise<void> | void;
  clearAllReaderPageCacheSettingsData: () => Promise<void> | void;
  clearCurrentBookReaderPageCacheSettingsData: () => Promise<void> | void;
  clearReaderSearchSettingsData: () => Promise<void> | void;
  clearOperationLogSettingsData: () => void;
  clearOrphanReaderRecordsSettingsData: () => Promise<void> | void;
  rebuildDatabaseIndexesSettingsData: () => Promise<void> | void;
  vacuumDatabaseSettingsData: () => Promise<void> | void;
  updateGlobalShortcutSetting: <K extends keyof Pick<ExtendedSettings, 'commandPaletteShortcut' | 'commandPaletteShowDescriptions' | 'commandPaletteSortMode' | 'importShortcut' | 'aiSummaryShortcut'>>(key: K, value: ExtendedSettings[K]) => void;
  updateNavigationShortcut: (key: keyof ExtendedSettings['navigationShortcuts'], value: ExtendedSettings['navigationShortcuts'][keyof ExtendedSettings['navigationShortcuts']]) => void;
  updateReaderShortcut: (key: keyof ExtendedSettings['readerShortcuts'], value: ExtendedSettings['readerShortcuts'][keyof ExtendedSettings['readerShortcuts']]) => void;
  restoreGlobalShortcutsDefaults: () => void;
  applyTaskLogRetentionPolicy: (value: ExtendedSettings['taskLogRetention']) => Promise<void> | void;
  updateCompletedTaskRetentionLimit: (value: string) => Promise<void> | void;
  updateOperationLogRetention: (value: string) => void;
  operationLogRetentionDays: (value: string) => number;
  refreshDiagnosticsRedactionPreview: () => void;
  exportOperationLogsSettingsData: (format: 'json' | 'ndjson') => void;
  exportApplicationDiagnosticsFromSettings: () => Promise<void> | void;
  exportAiDiagnosticsFromSettings: () => Promise<void> | void;
  exportIndexDiagnosticsFromSettings: () => Promise<void> | void;
  exportTaskDiagnosticsFromSettings: () => Promise<void> | void;
  exportReaderDiagnosticsFromSettings: () => void;
  copySystemInfoFromSettings: () => void;
  copyTauriCommandFailureInfo: () => void;
  loadOperationLogs: (retentionDays?: number) => OperationLogEntry[];
  clearOperationLogs: () => void;
  formatSettingsChangeTime: (isoTime: string) => string;
};

export { SettingsAnnotationPanel } from './SettingsAnnotationPanel';

export { SettingsLibraryPanel } from './SettingsLibraryPanel';
export { SettingsSearchPanel } from './SettingsSearchPanel';
export { SettingsDataPanel } from './SettingsDataPanel';

export { SettingsTasksPanel } from './SettingsTasksPanel';

export { SettingsShortcutPanel } from './SettingsShortcutPanel';

export { SettingsAccessibilityPanel } from './SettingsAccessibilityPanel';

export { SettingsDiagnosticsPanel } from './SettingsDiagnosticsPanel';
