import { useDeferredValue } from 'react';
import type { ReaderCustomPreset } from '../features/reader-core/readerSettings';
import { useI18n } from '../i18n';
import { setOperationLogLevel } from '../services/operationLogService';
import { extendedSettingsStorageKey, loadAiCustomSlashCommands, saveAiCustomSlashCommands, type ExtendedSettings } from '../services/settingsCenterService';
import { isTauriRuntime } from '../app/platform';
import { createSettingsDataMaintenanceActions } from '../features/settings-center/settingsCenterDataMaintenanceActions';
import { createSettingsDefaultResetActions } from '../features/settings-center/settingsCenterDefaultResetActions';
import { createSettingsDiagnosticsActions } from '../features/settings-center/settingsCenterDiagnosticsActions';
import { createSettingsGeneralActions } from '../features/settings-center/settingsCenterGeneralActions';
import { createSettingsChapterActions } from '../features/settings-center/settingsCenterChapterActions';
import { createSettingsSnapshotActions } from '../features/settings-center/settingsCenterSnapshotActions';
import { matchesSettingsSearchText, type SettingsGroupId } from '../features/settings-center/settingsCenterModel';
import { createSettingsCustomSlashCommandActions } from '../features/settings-center/settingsCenterCustomSlashCommandActions';
import { createSettingsAiActions } from '../features/settings-center/settingsCenterAiActions';
import { createSettingsAiProviderActions } from '../features/settings-center/settingsCenterAiProviderActions';
import { createSettingsReaderActions } from '../features/settings-center/settingsCenterReaderActions';
import { createSettingsSecurityActions } from '../features/settings-center/settingsCenterSecurityActions';
import type { SettingsImportPreview } from '../features/settings-center/settingsCenterImportModel';
import { downloadSettingsText, formatSettingsChangeTime } from '../features/settings-center/settingsCenterPageModel';
import { formatDataDirectoryMode, formatLocalEncryptionFallbackProtection, formatLocalEncryptionKeyStatus, formatSettingsByteSize, formatSettingsPageError } from '../features/settings-center/settingsCenterStatusFormatModel';
import { renderSettingsGroup } from './SettingsPageGroupRenderer';
import { buildSettingsGroupRendererProps, buildSettingsSupplementalPanelProps } from './SettingsPagePropsBuilders';
import { SettingsPageShell } from './SettingsPageShell';
import { useSettingsPageLifecycle } from './useSettingsPageLifecycle';
import { useSettingsPageOptions } from './useSettingsPageOptions';
import { saveSettingsPageMemory, useSettingsPageState } from './useSettingsPageState';
import { requestAppConfirm } from '../components/useAppConfirm';

export { settingsGroups, type SettingsGroupId } from '../features/settings-center/settingsCenterModel';
export function SettingsPage({ highlightTarget, initialGroup, currentBookId = '', currentBookTitle, onOpenCurrentBookSettings, onApplyPresetToCurrentBook }: { highlightTarget?: 'ai-api' | 'reader-memory-warning'; initialGroup?: SettingsGroupId; currentBookId?: string; currentBookTitle?: string; onOpenCurrentBookSettings?: () => void; onApplyPresetToCurrentBook?: (preset: ReaderCustomPreset) => void }) {
  const { locale, localePreference, setLocalePreference, t } = useI18n();
  const settingsPageState = useSettingsPageState(t);
  const { activeGroup, setActiveGroup, settingsQuery, setSettingsQuery, settings, setSettings, extendedSettings, setExtendedSettings, saveStatus, setSaveStatus } = settingsPageState;
  const deferredSettingsQuery = useDeferredValue(settingsQuery);
  const { operationLogs, setOperationLogs, operationLogFilterLevel, setOperationLogFilterLevel, operationLogFilterQuery, setOperationLogFilterQuery } = settingsPageState;
  const { readerGlobalSettings, setReaderGlobalSettings, readerCustomPresets, setReaderCustomPresets, readerPresetImportInputRef } = settingsPageState;
  const { chapterRules, setChapterRules, chapterRegexTestInput, setChapterRegexTestInput, compactSplitPreviewInput, setCompactSplitPreviewInput, txtCleanupPreviewInput, setTxtCleanupPreviewInput, chapterDiagnosticsSampleInput, setChapterDiagnosticsSampleInput, customCleanupRuleImportInputRef } = settingsPageState;
  const { settingsImportInputRef, showSettingsJsonPreview, setShowSettingsJsonPreview, settingsImportPreview, setSettingsImportPreview, settingsChangeHistory, setSettingsChangeHistory } = settingsPageState;
  const { diagnosticPaths, setDiagnosticPaths, diagnosticsRedactionPreview, setDiagnosticsRedactionPreview, lastTauriCommandFailure, setLastTauriCommandFailure, lastDataBackupResult, setLastDataBackupResult, selectedDataBackupPath, setSelectedDataBackupPath, dataBackupBusy, setDataBackupBusy } = settingsPageState;
  const { localEncryptionStatus, setLocalEncryptionStatus, loadingLocalEncryptionStatus, setLoadingLocalEncryptionStatus, localEncryptionStatusError, setLocalEncryptionStatusError, masterPasswordDraft, setMasterPasswordDraft, masterPasswordVerifyDraft, setMasterPasswordVerifyDraft, masterPasswordBusy, setMasterPasswordBusy, localKeyRotationBusy, setLocalKeyRotationBusy, lastLocalKeyRotationSummary, setLastLocalKeyRotationSummary } = settingsPageState;
  const { aiApiKeyStorageStatus, setAiApiKeyStorageStatus, loadingAiApiKeyStorageStatus, setLoadingAiApiKeyStorageStatus, aiApiKeyStorageStatusError, setAiApiKeyStorageStatusError, showApiKey, setShowApiKey, aiTestStatus, setAiTestStatus, aiModels, setAiModels, loadingAiModels, setLoadingAiModels, testingAi, setTestingAi, cloudRedactionPreviewInput, setCloudRedactionPreviewInput, customSlashCommandList, setCustomSlashCommandList, customSlashCommandDraft, setCustomSlashCommandDraft, customSlashCommandEditingId, setCustomSlashCommandEditingId, customSlashCommandEditDraft, setCustomSlashCommandEditDraft, customSlashCommandImportInputRef, highlightedSetting, setHighlightedSetting, aiApiSettingRef, readerMemoryWarningSettingRef } = settingsPageState;
  const { dataDirectoryStatus, setDataDirectoryStatus, dataDirectoryBusy, setDataDirectoryBusy, dataDirectoryError, setDataDirectoryError, dataDirectoryMigrationProgress, setDataDirectoryMigrationProgress } = settingsPageState;
  const {
    activeAiProviderProfile,
    activeSettingsGroup,
    aiCancelStrategyOptions,
    aiCitationCardDefaultDensityOptions,
    aiCitationDefaultSaveTargetOptions,
    aiCitationFieldStrictnessOptions,
    aiCommandScopeOptions,
    aiDefaultOutputFormatOptions,
    aiEndpointOptions,
    aiFtsUnavailableBehaviorOptions,
    aiModeOptions,
    aiModelOptions,
    aiMultiStageRetrievalModeOptions,
    aiNoSelectionFallbackScopeOptions,
    aiProviderKindOptions,
    aiProviderProfileOptions,
    aiProviderProfiles,
    aiReasoningEffortOptions,
    aiResponseFormatOptions,
    aiRetrievalQueryRewriteModeOptions,
    aiRetrievalStrategyOptions,
    aiSummaryShortcutOptions,
    aiScopeOptions,
    aiScopePriorityStrategyOptions,
    aiToolCallDisplayModeOptions,
    anchorRepairStrategyOptions,
    annotationCsvFieldOptions,
    annotationExportContentOptions,
    annotationJsonImportConflictStrategyOptions,
    appThemeOptions,
    availableAiModeOptions,
    backgroundTaskNotificationModeOptions,
    bookmarkGroupOptions,
    bookmarkSortOptions,
    bookTitleBracketModeOptions,
    chapterDiagnosticsCleanedContent,
    chapterParseDiagnostics,
    commandPaletteShortcutOptions,
    commandPaletteSortModeOptions,
    cloudRedactionPreview,
    dataAutoBackupFrequencyOptions,
    dataBackupModeOptions,
    defaultCoverLabelStrategyOptions,
    defaultCoverToneStrategyOptions,
    displaySettingsQuery,
    duplicateStrategyOptions,
    exportFormatOptions,
    filteredOperationLogs,
    fontRenderingDiagnostics,
    ftsRepairStrategyOptions,
    globalSearchModeOptions,
    highlightColorOptions,
    highlightColorShortcutOptions,
    highlightImportanceOptions,
    highlightOverlapStrategyOptions,
    highlightReviewStatusOptions,
    importFileFilterOptions,
    importShortcutOptions,
    indexPauseResumeStrategyOptions,
    indexRebuildStrategyOptions,
    indexStrategyVersionOptions,
    knowledgeDefaultColumnOptions,
    libraryDensityOptions,
    libraryFilterOptions,
    libraryNavigationShortcutOptions,
    librarySortOptions,
    libraryViewOptions,
    localeOptions,
    multiWindowConflictStrategyOptions,
    navItemOptions,
    normalizedSettingsQuery,
    noteDefaultSaveTargetOptions,
    operationLogFilterLevelOptions,
    operationLogOptions,
    pageTitleModeOptions,
    paragraphModeOptions,
    performanceTuningProfile,
    privacyAiApiKeyFallbackPath,
    privacyDiagnosticPaths,
    privacyLocalEncryptionFallbackPath,
    readerAiPanelShortcutOptions,
    readerAlignOptions,
    readerAnimationOptions,
    readerBookmarkShortcutOptions,
    readerCjkPunctuationOptions,
    readerFontWeightBoostOptions,
    readerHeaderFooterProgressFormatOptions,
    readerHeaderFooterTimeFormatOptions,
    readerHighlightShortcutOptions,
    readerInfoSlotOptions,
    readerLayoutOptions,
    readerLongParagraphStrategyOptions,
    readerMixedTextSpacingOptions,
    readerNavigationShortcutOptions,
    readerPageModeOptions,
    readerPageVerticalAlignOptions,
    readerPresetOptions,
    readerProgressModeOptions,
    readerSearchChapterFilterOptions,
    readerSearchHighlightColorOptions,
    readerSearchShortcutOptions,
    readerThemeOptions,
    readerTitleDecorationOptions,
    readerTitleNumberCleanupOptions,
    retentionSelectOptions,
    searchNavigationShortcutOptions,
    searchScopeOptions,
    settingsGroups,
    shortcutConflictMessages,
    startupOverviewModeOptions,
    startupPageOptions,
    taskCenterDefaultStatusFilterOptions,
    taskLogRetentionOptions,
    tocRuleChangeRebuildModeOptions,
    topbarButtonOptions,
    translationFallbackOptions,
    txtCleanupPreviewOutput,
    txtImportEncodingModeOptions,
    visibleGroups,
  } = useSettingsPageOptions({
    t,
    localePreference,
    diagnosticPaths,
    localEncryptionStatus,
    aiApiKeyStorageStatus,
    settings,
    extendedSettings,
    readerGlobalSettings,
    chapterRules,
    txtCleanupPreviewInput,
    chapterDiagnosticsSampleInput,
    operationLogs,
    operationLogFilterLevel,
    operationLogFilterQuery,
    aiModels,
    cloudRedactionPreviewInput,
    settingsQuery: deferredSettingsQuery,
    activeGroup,
  });
  const settingsDefaultResetActions = createSettingsDefaultResetActions({
    settings,
    extendedSettings,
    readerGlobalSettings,
    t,
    confirmReset: requestAppConfirm,
    setSettings,
    setOperationLogLevel,
    setReaderGlobalSettings,
    setChapterRules,
    setExtendedSettings,
    setAiTestStatus,
    setAiModels,
    setLocalePreference,
    setSaveStatus,
  });
  const {
    restoreReaderGlobalDefaults,
    restoreAllSettingsDefaults,
    restoreGroupDefaults,
  } = settingsDefaultResetActions;

  const settingsSecurityActions = createSettingsSecurityActions({
    getLocalEncryptionStatus: () => localEncryptionStatus,
    getMasterPasswordDraft: () => masterPasswordDraft,
    getMasterPasswordVerifyDraft: () => masterPasswordVerifyDraft,
    t,
    setAiApiKeyStorageStatus,
    setAiApiKeyStorageStatusError,
    setLoadingAiApiKeyStorageStatus,
    setLoadingLocalEncryptionStatus,
    setLastLocalKeyRotationSummary,
    setLocalEncryptionStatus,
    setLocalEncryptionStatusError,
    setLocalKeyRotationBusy,
    setMasterPasswordBusy,
    setMasterPasswordDraft,
    setMasterPasswordVerifyDraft,
    setSaveStatus,
    confirmRotate: requestAppConfirm,
    formatError: formatSettingsPageError,
  });
  const {
    refreshLocalEncryptionStatus,
    setMasterPasswordFromSettings,
    verifyMasterPasswordFromSettings,
    rotateLocalDataKeyFromSettings,
    refreshAiApiKeyStorageStatus,
  } = settingsSecurityActions;

  const settingsGeneralActions = createSettingsGeneralActions({
    getExtendedSettings: () => extendedSettings,
    getSettings: () => settings,
    highlightColorOptions,
    annotationCsvFieldOptions,
    knowledgeDefaultColumnOptions,
    taskLogRetentionOptions,
    t,
    refreshAiApiKeyStorageStatus,
    settingsGroups,
    setActiveGroup,
    setExtendedSettings,
    setOperationLogLevel,
    setOperationLogs,
    setSaveStatus,
    setSettings,
    setSettingsChangeHistory,
    setSettingsQuery,
    formatError: formatSettingsPageError,
  });
  const {
    onSettingsGroupNavKeyDown,
    updateAppSettings,
    updateAiProviderApiKey,
    updateTranslationApiKey,
    updateExtendedSetting,
    updateHighlightColorMeaning,
    updateHighlightColorShortcut,
    taskLogRetentionDays,
    applyTaskLogRetentionPolicy,
    updateCompletedTaskRetentionLimit,
    operationLogRetentionDays,
    updateOperationLogRetention,
    toggleAnnotationCsvField,
    toggleKnowledgeDefaultColumn,
    updateExtendedSettingsState,
    undoLastSettingsChangeFromHistory,
    updateGlobalShortcutSetting,
    updateNavigationShortcut,
    updateReaderShortcut,
    restoreGlobalShortcutsDefaults,
    updateVisibleNavItem,
    moveVisibleNavItem,
    restoreDefaultNavOrder,
    updateTopbarButtonVisibility,
  } = settingsGeneralActions;

  const settingsDataMaintenanceActions = createSettingsDataMaintenanceActions({
    currentBookId,
    currentBookTitle,
    extendedSettings,
    selectedDataBackupPath,
    operationLogRetentionDays,
    updateExtendedSetting,
    setSaveStatus,
    t,
    dataDirectoryStatus,
    setDataDirectoryStatus,
    setDataDirectoryBusy,
    setDataDirectoryError,
    setDataDirectoryMigrationProgress,
    setDiagnosticPaths,
    setDataBackupBusy,
    setLastDataBackupResult,
    setSelectedDataBackupPath,
    setOperationLogs,
    setLastTauriCommandFailure,
  });
  const {
    recordTauriCommandFailure,
    getDataDirectoryStatusFromSettings,
    useAppDataDirAsDefaultImportPath,
    openDataDirectoryFromSettings,
    chooseAndMigrateDataDirectoryFromSettings,
    enablePortableDataDirectoryFromSettings,
    createDataBackupFromSettings,
    chooseDataBackupDirectoryFromSettings,
    restoreDataBackupFromSettings,
    clearOperationLogSettingsData,
    exportOperationLogsSettingsData,
    clearCurrentBookReaderCacheSettingsData,
    clearAllReaderCacheSettingsData,
    clearCurrentBookReaderPageCacheSettingsData,
    clearAllReaderPageCacheSettingsData,
    clearCurrentBookAllDataSettingsData,
    clearOrphanReaderRecordsSettingsData,
    rebuildDatabaseIndexesSettingsData,
    vacuumDatabaseSettingsData,
    clearCurrentBookCloudAiHistorySettingsData,
    clearAllCloudAiHistorySettingsData,
    exportCurrentBookCloudAiHistoryDiagnostics,
    exportAllCloudAiHistoryDiagnostics,
    allowCurrentBookCloudAiSettingsData,
    revokeCurrentBookCloudAiConsentSettingsData,
    clearReaderSearchSettingsData,
  } = settingsDataMaintenanceActions;

  useSettingsPageLifecycle({
    ...settingsPageState,
    t,
    highlightTarget,
    initialGroup,
    getDataDirectoryStatusFromSettings,
    refreshLocalEncryptionStatus,
    refreshAiApiKeyStorageStatus,
    operationLogRetentionDays,
  });
  const settingsAiProviderActions = createSettingsAiProviderActions({
    getSettings: () => settings,
    updateAppSettings,
    updateAiProviderApiKey,
    setSaveStatus,
    setAiModels,
    confirmDelete: requestAppConfirm,
    t,
  });
  const { updateAiProviderProfile, selectAiProviderProfile, createAiProviderProfile, copyCurrentAiConfigAsProvider, deleteAiProviderProfile, applyAiProviderProfile, addAiProviderModels, selectAiProviderModel, updateAiProviderModelSettings, removeAiProviderModel, resetAiProviderModels } = settingsAiProviderActions;

  const settingsReaderActions = createSettingsReaderActions({
    getReaderGlobalSettings: () => readerGlobalSettings,
    setReaderGlobalSettings,
    getReaderCustomPresets: () => readerCustomPresets,
    setReaderCustomPresets,
    setSettingsChangeHistory,
    setSaveStatus,
    t,
    refreshLocalEncryptionStatus,
    onApplyPresetToCurrentBook,
    formatError: formatSettingsPageError,
  });
  const {
    updateReaderGlobalSetting,
    updateReaderFontStack,
    parseReaderFontFallbackInput,
    applyReaderGlobalPreset,
    saveCurrentReaderSettingsAsPreset,
    applyReaderCustomPreset,
    renameReaderCustomPresetFromSettings,
    deleteReaderCustomPresetFromSettings,
    exportReaderCustomPresetsFromSettings,
    importReaderCustomPresetsFromSettings,
    applyReaderCustomPresetToCurrentBook,
  } = settingsReaderActions;

  const settingsChapterActions = createSettingsChapterActions({
    chapterRules,
    extendedSettings,
    setChapterRules,
    setExtendedSettings,
    setSettingsChangeHistory,
    setSaveStatus,
    t,
    formatError: formatSettingsPageError,
  });
  const {
    updateChapterRule,
    addChapterRegexRule,
    updateChapterRegexRule,
    moveChapterRegexRule,
    removeChapterRegexRule,
    addCustomCleanupRule,
    updateCustomCleanupRule,
    moveCustomCleanupRule,
    removeCustomCleanupRule,
    addTocTitleGroupRule,
    updateTocTitleGroupRule,
    moveTocTitleGroupRule,
    removeTocTitleGroupRule,
    exportCustomCleanupRulesFromSettings,
    importCustomCleanupRulesFromSettings,
  } = settingsChapterActions;

  const settingsAiActions = createSettingsAiActions({
    getExtendedSettings: () => extendedSettings,
    getSettings: () => settings,
    setAiModels,
    setAiTestStatus,
    setExtendedSettings,
    setLoadingAiModels,
    setSettingsChangeHistory,
    setSaveStatus,
    setTestingAi,
    t,
    updateAppSettings,
    updateExtendedSetting,
  });
  const {
    updateCloudAiEnabledSetting,
    updateLocalAiEnabledSetting,
    updateDefaultAiModeSetting,
    updateAiCommandDefaultScope,
    updateAiBuiltInSlashCommandEnabled,
    updateAiCommandRetrievalStrategy,
    runAiConnectionTest,
    loadAiModels,
  } = settingsAiActions;

  const settingsCustomSlashCommandActions = createSettingsCustomSlashCommandActions({
    getCustomSlashCommandList: () => customSlashCommandList,
    setCustomSlashCommandList,
    getCustomSlashCommandDraft: () => customSlashCommandDraft,
    setCustomSlashCommandDraft,
    getCustomSlashCommandEditingId: () => customSlashCommandEditingId,
    setCustomSlashCommandEditingId,
    getCustomSlashCommandEditDraft: () => customSlashCommandEditDraft,
    setCustomSlashCommandEditDraft,
    getAiCustomSlashCommandLimit: () => extendedSettings.aiCustomSlashCommandLimit,
    setSaveStatus,
    t,
    loadAiCustomSlashCommands,
    saveAiCustomSlashCommands,
    downloadSettingsText,
    formatError: formatSettingsPageError,
  });
  const {
    refreshCustomSlashCommandList,
    createCustomSlashCommandFromSettings,
    startEditingCustomSlashCommand,
    cancelCustomSlashCommandEdit,
    saveCustomSlashCommandEdit,
    deleteCustomSlashCommandFromSettings,
    exportCustomSlashCommandsFromSettings,
    importCustomSlashCommandsFromSettings,
    addCustomSlashCommandTemplate,
  } = settingsCustomSlashCommandActions;

  const settingsSnapshotActions = createSettingsSnapshotActions({
    settings,
    readerGlobalSettings,
    chapterRules,
    extendedSettings,
    settingsImportPreview,
    setReaderGlobalSettings,
    setChapterRules,
    setExtendedSettings,
    setSettingsImportPreview,
    setSaveStatus,
    updateAppSettings,
    t,
  });
  const {
    buildSettingsSnapshot,
    buildSettingsJsonPreview,
    exportSettingsSnapshot,
    importSettingsSnapshot,
    confirmSettingsImportPreview,
  } = settingsSnapshotActions;

  const settingsDiagnosticsActions = createSettingsDiagnosticsActions({
    settings,
    extendedSettings,
    readerGlobalSettings,
    chapterRules,
    diagnosticPaths,
    localEncryptionStatus,
    aiApiKeyStorageStatus,
    aiTestStatus,
    aiModels,
    customSlashCommandList,
    fontRenderingDiagnostics,
    chapterParseDiagnostics,
    chapterDiagnosticsCleanedContent,
    lastTauriCommandFailure,
    saveStatus,
    t,
    operationLogRetentionDays,
    buildSettingsSnapshot,
    recordTauriCommandFailure,
    setDiagnosticsRedactionPreview,
    setSaveStatus,
  });
  const {
    copyDiagnosticSettingsSnapshot,
    refreshDiagnosticsRedactionPreview,
    exportTaskDiagnosticsFromSettings,
    exportApplicationDiagnosticsFromSettings,
    exportAiDiagnosticsFromSettings,
    exportReaderDiagnosticsFromSettings,
    exportIndexDiagnosticsFromSettings,
    copySystemInfoFromSettings,
    copyTauriCommandFailureInfo,
    copyChapterParseDiagnostics,
  } = settingsDiagnosticsActions;

  const settingsPagePropsContext = {
    ...settingsPageState,
    ...settingsDataMaintenanceActions,
    ...settingsDefaultResetActions,
    ...settingsAiActions,
    ...settingsAiProviderActions,
    ...settingsReaderActions,
    ...settingsSecurityActions,
    ...settingsChapterActions,
    ...settingsCustomSlashCommandActions,
    ...settingsSnapshotActions,
    ...settingsDiagnosticsActions,
    t,
    locale,
    localePreference,
    setLocalePreference,
    settings,
    extendedSettings,
    readerGlobalSettings,
    currentBookId,
    currentBookTitle,
    onOpenCurrentBookSettings,
    onApplyPresetToCurrentBook,
    diagnosticPaths,
    privacyDiagnosticPaths,
    privacyLocalEncryptionFallbackPath,
    privacyAiApiKeyFallbackPath,
    dataDirectoryStatus,
    dataDirectoryBusy,
    dataDirectoryError,
    filteredOperationLogs,
    performanceTuningProfile,
    shortcutConflictMessages,
    fontRenderingDiagnostics,
    localeOptions,
    translationFallbackOptions,
    retentionSelectOptions,
    libraryViewOptions,
    librarySortOptions,
    libraryFilterOptions,
    duplicateStrategyOptions,
    defaultCoverToneStrategyOptions,
    defaultCoverLabelStrategyOptions,
    importFileFilterOptions,
    txtImportEncodingModeOptions,
    libraryDensityOptions,
    searchScopeOptions,
    globalSearchModeOptions,
    readerSearchChapterFilterOptions,
    readerSearchHighlightColorOptions,
    indexStrategyVersionOptions,
    ftsRepairStrategyOptions,
    indexRebuildStrategyOptions,
    indexPauseResumeStrategyOptions,
    highlightColorOptions,
    highlightColorShortcutOptions,
    highlightImportanceOptions,
    highlightReviewStatusOptions,
    highlightOverlapStrategyOptions,
    anchorRepairStrategyOptions,
    exportFormatOptions,
    annotationExportContentOptions,
    annotationJsonImportConflictStrategyOptions,
    noteDefaultSaveTargetOptions,
    annotationCsvFieldOptions,
    knowledgeDefaultColumnOptions,
    bookmarkSortOptions,
    bookmarkGroupOptions,
    dataAutoBackupFrequencyOptions,
    dataBackupModeOptions,
    backgroundTaskNotificationModeOptions,
    taskCenterDefaultStatusFilterOptions,
    commandPaletteShortcutOptions,
    commandPaletteSortModeOptions,
    readerNavigationShortcutOptions,
    libraryNavigationShortcutOptions,
    searchNavigationShortcutOptions,
    importShortcutOptions,
    aiSummaryShortcutOptions,
    readerHighlightShortcutOptions,
    readerBookmarkShortcutOptions,
    readerAiPanelShortcutOptions,
    readerSearchShortcutOptions,
    operationLogOptions,
    operationLogFilterLevelOptions,
    taskLogRetentionOptions,
    startupPageOptions,
    startupOverviewModeOptions,
    readerPresetOptions,
    readerThemeOptions,
    readerLayoutOptions,
    readerPageModeOptions,
    readerPageVerticalAlignOptions,
    readerLongParagraphStrategyOptions,
    readerCjkPunctuationOptions,
    readerMixedTextSpacingOptions,
    readerFontWeightBoostOptions,
    readerAlignOptions,
    readerTitleNumberCleanupOptions,
    readerTitleDecorationOptions,
    readerInfoSlotOptions,
    readerHeaderFooterTimeFormatOptions,
    readerHeaderFooterProgressFormatOptions,
    readerAnimationOptions,
    multiWindowConflictStrategyOptions,
    readerProgressModeOptions,
    tocRuleChangeRebuildModeOptions,
    paragraphModeOptions,
    bookTitleBracketModeOptions,
    appThemeOptions,
    pageTitleModeOptions,
    topbarButtonOptions,
    navItemOptions,
    aiModelOptions,
    aiProviderProfiles,
    activeAiProviderProfile,
    aiProviderProfileOptions,
    aiProviderKindOptions,
    aiEndpointOptions,
    aiCancelStrategyOptions,
    aiReasoningEffortOptions,
    aiResponseFormatOptions,
    aiModeOptions,
    availableAiModeOptions,
    aiScopeOptions,
    aiCommandScopeOptions,
    aiNoSelectionFallbackScopeOptions,
    aiScopePriorityStrategyOptions,
    aiRetrievalStrategyOptions,
    aiRetrievalQueryRewriteModeOptions,
    aiMultiStageRetrievalModeOptions,
    aiFtsUnavailableBehaviorOptions,
    aiDefaultOutputFormatOptions,
    aiCitationCardDefaultDensityOptions,
    aiCitationFieldStrictnessOptions,
    aiToolCallDisplayModeOptions,
    aiCitationDefaultSaveTargetOptions,
    cloudRedactionPreview,
    txtCleanupPreviewOutput,
    chapterDiagnosticsCleanedContent,
    chapterParseDiagnostics,
    updateAppSettings,
    updateTranslationApiKey,
    updateExtendedSetting,
    updateReaderGlobalSetting,
    toggleAnnotationCsvField,
    toggleKnowledgeDefaultColumn,
    updateHighlightColorMeaning,
    updateHighlightColorShortcut,
    refreshLocalEncryptionStatus,
    setMasterPasswordFromSettings,
    verifyMasterPasswordFromSettings,
    rotateLocalDataKeyFromSettings,
    updateGlobalShortcutSetting,
    updateNavigationShortcut,
    updateReaderShortcut,
    restoreGlobalShortcutsDefaults,
    applyTaskLogRetentionPolicy,
    updateCompletedTaskRetentionLimit,
    updateOperationLogRetention,
    operationLogRetentionDays,
    undoLastSettingsChangeFromHistory,
    updateTopbarButtonVisibility,
    updateVisibleNavItem,
    moveVisibleNavItem,
    restoreDefaultNavOrder,
    refreshAiApiKeyStorageStatus,
    runAiConnectionTest,
    loadAiModels,
    updateCloudAiEnabledSetting,
    updateLocalAiEnabledSetting,
    updateDefaultAiModeSetting,
    updateAiCommandDefaultScope,
    updateAiBuiltInSlashCommandEnabled,
    updateAiCommandRetrievalStrategy,
  };
  const supplementalPanelProps = buildSettingsSupplementalPanelProps(settingsPagePropsContext);
  const groupRendererProps = buildSettingsGroupRendererProps({
    ...settingsPagePropsContext,
    settingsPageState,
    supplementalPanelProps,
  });
  const renderedSettingsGroups = visibleGroups.map((group) => {
    const content = renderSettingsGroup(group, groupRendererProps);
    const groupMatchesSearch = matchesSettingsSearchText(normalizedSettingsQuery, [group.label, group.description, group.id]);
    return { group, content, groupMatchesSearch };
  });

  return (
    <SettingsPageShell
      activeGroup={activeGroup} activeSettingsGroup={activeSettingsGroup}
      displaySettingsQuery={displaySettingsQuery} normalizedSettingsQuery={normalizedSettingsQuery}
      onSettingsGroupNavKeyDown={onSettingsGroupNavKeyDown} renderedSettingsGroups={renderedSettingsGroups}
      restoreGroupDefaults={restoreGroupDefaults}
      settingsGroups={settingsGroups}
      setActiveGroup={(groupId) => { saveSettingsPageMemory({ activeGroup: groupId, settingsQuery: '' }); setActiveGroup(groupId); }} setSettingsQuery={setSettingsQuery} settingsQuery={settingsQuery}
      t={t}
    />
  );
}
