import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const panel = readFileSync(new URL('./ReaderHighlightPanel.tsx', import.meta.url), 'utf8');
const readerPage = readFileSync(new URL('./ReaderPage.tsx', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../../app/styles/settings.css', import.meta.url), 'utf8');
const readerStyles = readFileSync(new URL('../../app/readerStyles.css', import.meta.url), 'utf8');

assert.match(panel, /import \{ BookMindIcon/u, 'Highlight panel actions should use BookMind paper-geometry icons');
assert.match(panel, /function HighlightPanelIconButton/u, 'Highlight panel should render compact icon action buttons');
assert.match(panel, /function stopReaderHighlightPanelWheel/u, 'Highlight panel should have a dedicated wheel propagation guard');
assert.match(panel, /nativeEvent\.stopImmediatePropagation\(\)/u, 'Highlight panel wheel guard should stop native reader wheel listeners');
assert.match(panel, /onWheelCapture=\{stopReaderHighlightPanelWheel\}/u, 'Highlight panel should stop wheel events during capture before reader pagination sees them');
assert.match(panel, /activeAnnotationTab/u, 'Highlight panel should keep separate highlight/bookmark tabs');
assert.match(panel, /className="reader-annotation-tabs"/u, 'Highlight panel should render a top tab switcher for highlights and bookmarks');
assert.match(panel, /role="tablist"/u, 'Highlight/bookmark switcher should expose tab semantics');
assert.match(panel, /activeAnnotationTab === 'bookmarks'/u, 'Bookmark management should only render inside the bookmark tab');
assert.match(panel, /activeAnnotationTab === 'highlights'/u, 'Highlight management should only render inside the highlight tab');
assert.match(panel, /useState<Set<number>>\(\(\) => new Set\(\)\)/u, 'Highlight chapter groups should start collapsed by default');
assert.match(panel, /reader\.highlight\.expandAllGroups[\s\S]*setExpandedHighlightGroups\(new Set\(highlightGroups\.map/u, 'Highlight panel should expose one-click expansion for all filtered chapter groups');
assert.match(panel, /reader\.highlight\.collapseAllGroups[\s\S]*setExpandedHighlightGroups\(new Set\(\)\)/u, 'Highlight panel should expose one-click collapse for all chapter groups');
assert.match(panel, /className="reader-highlight-group-toggle"[\s\S]*aria-expanded=\{expanded\}[\s\S]*libraryGroupCollapse[\s\S]*libraryGroupExpand/u, 'Each highlight chapter heading should independently expose and toggle its expanded state');
assert.match(panel, /reader-highlight-action-btn/u, 'Highlight action buttons should share a fixed icon-button class');
assert.match(panel, /data-tooltip=\{label\}/u, 'Highlight icon buttons should expose hover tooltip text');
assert.match(panel, /function HighlightPanelTabButton[\s\S]*createPortal\(<span className="reader-highlight-tooltip" role="tooltip"/u, 'Highlight and bookmark tabs should portal their tooltips outside the scroll container');
assert.match(panel, /className="reader-import-json reader-annotation-import-btn"/u, 'Import JSON should render as a labeled action inside the advanced floating popover');
assert.match(panel, /className="reader-annotation-advanced-popover"/u, 'Advanced annotation actions should open in a floating popover instead of covering the toolbar');
assert.match(panel, /className="reader-annotation-advanced-popover"[\s\S]*reader-highlight-controls[\s\S]*reader-bookmark-bulk-edit/u, 'Advanced filters and bulk edit should live inside the floating popover');
assert.match(panel, /setAdvancedControlsOpen\(false\);\s*setExportPanelOpen\(false\);/u, 'Floating advanced/export panels should dismiss together on outside click or Escape');
assert.match(panel, /annotation-export-select"[\s\S]{0,240}menuPlacement="bottom"/u, 'Export format select should open downward inside the panel');
assert.equal((panel.match(/menuPlacement="bottom"/gu) ?? []).length >= 8, true, 'Highlight and bookmark panel selects should open downward consistently');

assert.match(styles, /\.reader-highlight-panel \{[^}]*box-sizing:\s*border-box/u, 'Highlight panel should size itself without leaking past its bounds');
assert.match(panel, /reader-overlay-panel reader-panel-highlights placement-\$\{panelPlacement\}/u, 'Highlight panel should use the shared overlay shell so left gutters match research desk');
assert.match(panel, /setReaderRightPanelPlacement\('search', panelPlacement\)/u, 'Search results should share the highlight shell placement and right-rail geometry');
assert.match(panel, /const showReaderSearchResults = searchPanelOpen/u, 'Search session should keep its result body mounted even before a query is entered');
assert.match(panel, /className="reader-search-results-panel"/u, 'Search results should use a dedicated scrollable right-panel body');
assert.match(readerStyles, /\.reader-highlight-panel > \.reader-search-results-panel \{[^}]*overflow-y:\s*auto/u, 'Search results should scroll within the shared right-panel height');
assert.match(styles, /\.reader-highlight-panel \{[^}]*max-height:\s*none/u, 'Highlight panel height should come from the shared overlay shell instead of viewport height');
assert.match(styles, /\.reader-annotation-scroll \{[^}]*overflow-y:\s*auto/u, 'Highlight panel content should scroll internally');
assert.match(styles, /\.reader-annotation-tabs \{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,1fr\)\)/u, 'Highlight panel should style highlight/bookmark tabs as two equal paper controls');
assert.match(styles, /\.reader-annotation-tabs button \{[^}]*min-width:\s*0/u, 'Annotation tabs should stay inside the panel width');
assert.match(styles, /\.reader-annotation-tabs button\.active \{[^}]*background:\s*var\(--ink-0\)/u, 'Active annotation tab should have a clear selected state');
assert.match(styles, /\.reader-annotation-io \{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\) repeat\(2,\s*42px\)/u, 'Annotation import/export row should reserve fixed icon columns');
assert.match(styles, /\.reader-highlight-selection-actions \{[^}]*display:\s*flex/u, 'Bulk selection actions should flex so hidden disabled actions do not leave empty slots');
assert.match(panel, /hideWhenDisabled/u, 'Selection actions that cannot run should hide instead of rendering disabled');
assert.match(styles, /\.reader-annotation-advanced-popover \{[^}]*position:\s*absolute/u, 'Advanced annotation actions should float over the panel instead of pushing the toolbar');
assert.match(styles, /\.reader-annotation-import-btn \{[^}]*grid-template-columns:\s*22px minmax\(0,1fr\)/u, 'Import JSON should render as a labeled floating action button');
assert.match(styles, /\.reader-highlight-action-btn \{[^}]*width:\s*42px/u, 'Highlight action icon buttons should have fixed width');
assert.match(styles, /\.reader-highlight-action-btn \{[^}]*height:\s*42px/u, 'Highlight action icon buttons should have fixed height');
assert.match(styles, /\.reader-highlight-action-btn \{[^}]*z-index:\s*2/u, 'Highlight action buttons need their own stacking layer');
assert.match(styles, /\.reader-highlight-action-btn:hover:not\(:disabled\), \.reader-highlight-action-btn:focus-visible:not\(:disabled\) \{[^}]*z-index:\s*260/u, 'Highlight action buttons should render above adjacent controls while hovered');
assert.match(panel, /<HighlightPanelIconButton[^>]*icon="more"[^>]*label=\{t\('reader\.more'\)\}/u, 'More actions should use the unclipped portal tooltip button');
assert.match(panel, /className="reader-highlight-panel-close".*tooltipAlign="right"/u, 'Close should use a right-aligned portal tooltip that stays inside the viewport');
assert.doesNotMatch(styles, /\.reader-highlight-action-btn:hover::after/u, 'Highlight action tooltips must not use pseudo-elements that are clipped by scrolling rows');
assert.match(styles, /\.reader-highlight-tooltip\.align-right \{[^}]*transform:\s*none/u, 'Right-edge highlight tooltips should align without translating beyond the viewport');
assert.match(styles, /\.reader-highlight-action-btn > \.bm-icon \{[^}]*width:\s*22px/u, 'Highlight action icons should have stable geometry');
assert.match(styles, /\.reader-annotation-toolbar-actions \.reader-highlight-action-btn > \.bm-icon \{[^}]*transform:\s*translate\(-50%,\s*-50%\)/u, 'Toolbar more/close icons should be absolutely centered inside their buttons');
assert.match(styles, /\.reader-annotation-toolbar \{[^}]*overflow-x:\s*auto/u, 'Top annotation toolbar should scroll horizontally like the second action row when the panel is narrow');
assert.doesNotMatch(styles, /\.reader-annotation-tabs button:hover::after/u, 'Annotation tab tooltips must not use pseudo-elements that are clipped by the horizontal toolbar');
assert.match(styles, /\.reader-annotation-toolbar-actions \{[^}]*gap:\s*12px/u, 'More and close actions should keep clear spacing instead of sticking together');
assert.match(styles, /\.reader-annotation-toolbar-actions \{[^}]*border-left:/u, 'More/close cluster should be separated from the search field by a paper divider');
assert.match(styles, /\.reader-annotation-toolbar-actions \{[^}]*flex:\s*0\s*0\s*auto/u, 'Close/more actions must not shrink away when the panel width is reduced');
assert.match(styles, /\.reader-highlight-action-btn > \.bm-icon \{[^}]*left:\s*50%[^}]*top:\s*50%/u, 'Highlight action icons should center with left/top 50% offsets');
assert.match(panel, /className="reader-annotation-toolbar-actions"/u, 'More and close buttons should share a dedicated action cluster');
assert.match(panel, /className="reader-overlay-resize-grip reader-highlight-panel-resize-grip"/u, 'Highlight panel should expose a research-desk style width resize grip');
assert.match(panel, /HIGHLIGHT_PANEL_MIN_WIDTH[\s\S]*HIGHLIGHT_PANEL_MAX_WIDTH[\s\S]*startPanelWidthDrag/u, 'Highlight panel width should be drag-resizable between min and max bounds');
assert.match(panel, /setReaderRightPanelWidth/u, 'Highlight panel resize should update the shared right-rail width');
assert.doesNotMatch(panel, /bookmind:reader-highlight-panel-width/u, 'Highlight panel must not persist an independent width key');
assert.match(panel, /reader-highlight-panel-dock-handle/u, 'Highlight panel should expose a top dock handle like the research desk');
assert.match(panel, /startPanelDockDrag/u, 'Highlight panel should support dragging to the right sidebar placement');
assert.match(panel, /placement-\$\{panelPlacement\}/u, 'Highlight panel should switch between floating and sidebar placements');
assert.match(readerStyles, /\.reader-overlay-resize-grip \{[^}]*cursor:\s*ew-resize/u, 'Highlight panel resize grip should use the shared overlay horizontal resize cursor');
assert.match(readerStyles, /\.reader-overlay-panel \{[^}]*min-width:\s*340px/u, 'Highlight shell should keep a research-desk style minimum width');
assert.match(readerStyles, /\.reader-overlay-panel \{[^}]*top:\s*var\(--reader-panel-body-top/u, 'Floating highlight shell should start below the fixed session tabstrip');
assert.match(readerStyles, /\.reader-overlay-panel\.placement-sidebar \{[^}]*grid-column:\s*2/u, 'Docked highlight shell should occupy the right stage column');
assert.match(readerStyles, /\.reader-overlay-panel\.placement-sidebar \{[^}]*margin:\s*var\(--reader-panel-body-top\) 12px 12px/u, 'Docked highlight shell should share the floating panel gutters below the fixed session tabstrip');
assert.match(readerStyles, /\.reader-highlight-group-toggle \{[^}]*grid-template-columns:\s*20px minmax\(0,1fr\) auto/u, 'Collapsible highlight chapter headings should keep icon, title, and count aligned');
assert.match(readerStyles, /\.reader-highlight-group-items\[hidden\] \{[^}]*display:\s*none/u, 'Collapsed highlight chapter groups should remove their rows from layout');
assert.match(styles, /\.reader-highlight-panel \.themed-select-menu \{[^}]*max-height:\s*min\(260px,\s*44vh\)/u, 'Highlight dropdown menus should cap their height');
assert.match(styles, /\.reader-highlight-panel \.themed-select-menu \{[^}]*overflow-y:\s*auto/u, 'Highlight dropdown menus should scroll vertically');
assert.match(styles, /\.reader-highlight-panel \.themed-select-menu \{[^}]*overscroll-behavior:\s*contain/u, 'Highlight dropdown scrolling should stay inside the menu');
assert.match(styles, /\.reader-highlight-panel \.themed-select\.open \{[^}]*z-index:\s*190/u, 'Open highlight selects should render above neighboring controls');
assert.match(styles, /\.reader-highlight-panel \.themed-select-trigger \{[^}]*height:\s*100%/u, 'Highlight select trigger should stay inside the select frame');
assert.match(styles, /\.reader-highlight-panel \.themed-select-trigger \{[^}]*background:\s*transparent/u, 'Highlight select trigger should not draw a second oversized inner pill');
assert.match(styles, /\.reader-highlight-panel \.themed-select-trigger:focus-visible \{[^}]*outline-offset:\s*-3px/u, 'Highlight select focus ring should remain inside the select frame');
assert.match(styles, /\.reader-highlight-panel \.themed-select-menu button \{[^}]*grid-template-columns:\s*20px minmax\(0,1fr\) 20px/u, 'Dropdown options should keep centered labels and checkmarks inside the rounded menu');

assert.match(readerStyles, /\.reader-grid\.highlight-panel-docked \{[^}]*grid-template-columns:\s*minmax\(0,1fr\) minmax\(364px, calc\(var\(--reader-right-panel-width[^}]*\+ 24px\)/u, 'Docked highlight panel should reserve the same shared width and outer gutters as AI/settings');
assert.match(panel, /createPortal\(panelNode, panelHost\)/u, 'Dockable highlight panel should render into the workspace reader-grid host');
assert.match(readerStyles, /\.reader-highlight-menu \{[^}]*position:\s*fixed/u, 'Highlight item context menu should be viewport-positioned instead of clipped by the highlight panel scroll area');
assert.match(readerStyles, /\.reader-highlight-menu \{[^}]*z-index:\s*240/u, 'Highlight item context menu should render above the highlight panel');
assert.match(readerStyles, /\.reader-highlight-menu \{[^}]*max-height:\s*calc\(100vh - 16px\)/u, 'Highlight item context menu should stay inside the viewport height');
assert.match(readerStyles, /\.reader-highlight-menu \{[^}]*overflow:\s*auto/u, 'Highlight item context menu should scroll internally when space is constrained');
assert.match(readerStyles, /\.reader-highlight-menu \{[^}]*width:\s*max-content[^}]*min-width:\s*0[^}]*max-width:\s*min\(320px, calc\(100vw - 16px\)\)/u, 'Annotation context menus should size to their longest action without a fixed minimum width');
assert.match(readerStyles, /\.reader-highlight-menu\.reader-bookmark-menu \.reader-color-row \{[^}]*grid-template-columns:\s*repeat\(3, 32px\)/u, 'Bookmark context-menu colors should render as three columns across two rows');
assert.match(readerStyles, /\.reader-highlight-menu \.reader-color-row \{[^}]*grid-template-columns:\s*repeat\(3, 32px\)[^}]*gap:\s*6px/u, 'Highlight context-menu colors should use the same compact grid as bookmarks');
assert.match(readerStyles, /\.reader-highlight-menu \.reader-color-row \.reader-color-dot \{[^}]*width:\s*32px[^}]*height:\s*32px[^}]*min-height:\s*32px/u, 'Highlight context-menu color dots should override later panel and touch-target sizing to match bookmark dots');
assert.match(readerPage, /resolveReaderHighlightMenuPosition/u, 'Highlight item context menu should have viewport clamping logic');
assert.match(readerPage, /opener\.closest<HTMLElement>\('\.reader-highlight-panel'\)\?\.getBoundingClientRect\(\)/u, 'Highlight menus opened from annotation rows should use the right panel as their boundary');
assert.match(readerPage, /\?\? scrollRef\.current\?\.getBoundingClientRect\(\)/u, 'Highlight menus opened from reading content should retain the reading-area boundary');
assert.match(readerPage, /const position = resolveReaderHighlightMenuPosition\(clientX, clientY, containerRect/u, 'Highlight item context menu should use its active surface boundary for clamped coordinates');
assert.match(panel, /bounds: panelRect \? \{ left: panelRect\.left, top: panelRect\.top, right: panelRect\.right, bottom: panelRect\.bottom \} : undefined/u, 'Bookmark menus opened from annotation rows should retain the right-panel boundary');
assert.match(readerPage, /highlightMenu \? createPortal\(<ReaderHighlightContextMenu[\s\S]*document\.body\)/u, 'Highlight menus should portal above the reader canvas so right-panel coordinates are not clipped');
assert.match(panel, /bookmarkMenu \? createPortal\(<ReaderBookmarkContextMenu[\s\S]*document\.body\)/u, 'Bookmark menus should portal above the annotation panel overflow boundary');
assert.doesNotMatch(readerPage, /setHighlightMenu\(\{[\s\S]{0,180}scrollLeft/u, 'Highlight item context menu should not add scroll container offsets to fixed viewport coordinates');
assert.doesNotMatch(readerPage, /setHighlightMenu\(\{[\s\S]{0,180}scrollTop/u, 'Highlight item context menu should not add scroll container offsets to fixed viewport coordinates');

console.log('Verified reader highlight panel layout contract.');
