import type { MoyuReaderProfile } from '../../features/reader-core/moyuReaderSettingsModel';

export type LocalEncryptionStatus = {
  algorithm: 'AES-256-GCM' | string;
  envelopeVersion: 'local-envelope-v1' | string;
  keyStatus: 'available' | 'missing' | 'error' | string;
  activeKeyId: string;
  retiredKeyCount: number;
  masterPasswordEnabled: boolean;
  fallbackProtection: 'masterPassword' | 'plaintextFile' | 'keyringOnly' | 'none' | string;
  keyringAvailable: boolean;
  fallbackFileExists: boolean;
  fallbackFilePath: string;
  wrappedFallbackFileExists: boolean;
  wrappedFallbackFilePath: string;
  protectedKinds: string[];
  nonceBytes: number;
  keyBytes: number;
};

export type LocalDataKeyRotationResult = {
  previousKeyId: string;
  activeKeyId: string;
  reencryptedReaderRecords: number;
  reencryptedNoteFiles: number;
  retiredKeyCount: number;
};

export type AiApiKeyStorageStatus = {
  keyStatus: 'saved' | 'missing' | 'error' | string;
  primaryStore: 'keyring' | 'fallbackFile' | 'none' | string;
  keyringAvailable: boolean;
  keyringHasKey: boolean;
  fallbackFileExists: boolean;
  fallbackFileHasKey: boolean;
  fallbackFilePath: string;
};

export type ExtendedSettings = {
  startupPage: 'overview' | 'reader' | 'library' | 'last';
  openLastReaderBookOnStartup: boolean;
  restoreLastReaderPositionOnStartup: boolean;
  checkUnfinishedTasksOnStartup: boolean;
  refreshLibraryMetadataOnStartup: boolean;
  startupOverviewMode: 'auto' | 'welcome' | 'recent' | 'emptyGuide';
  rememberWindowGeometry: boolean;
  backgroundTaskNotificationMode: 'silent' | 'toast' | 'system-notification';
  refreshLibraryOnTaskCompletion: boolean;
  taskAutoRunQueuedWhenIdle: boolean;
  taskCenterDefaultStatusFilter: 'all' | 'queued' | 'running' | 'paused' | 'cancelling' | 'cancelled' | 'failed' | 'succeeded' | 'skipped' | 'archived';
  confirmOpenExternalPath: boolean;
  autoShowTaskCenterForLongOperations: boolean;
  errorDetailsDefaultExpanded: boolean;
  appTheme: 'light' | 'dark' | 'system';
  customThemeColor: string;
  sidebarCollapsed: boolean;
  libraryPanelPersistent: boolean;
  sidebarRecentBookLimit: string;
  pageTitleMode: 'full' | 'compact';
  visibleNavItems: Array<'overview' | 'reader' | 'library' | 'knowledge' | 'characters' | 'search' | 'tasks' | 'settings'>;
  topbarButtonVisibility: {
    command: boolean;
    night: boolean;
    search: boolean;
    aiSummary: boolean;
  };
  readerThemeFollowsApp: boolean;
  globalShortcutsEnabled: boolean;
  commandPaletteIncludesSettings: boolean;
  commandPaletteShortcut: 'ctrl-k' | 'ctrl-p' | 'ctrl-shift-p' | 'disabled';
  commandPaletteShowDescriptions: boolean;
  commandPaletteSortMode: 'fixed' | 'recent';
  navigationShortcuts: {
    reader: 'ctrl-b' | 'ctrl-r' | 'disabled';
    library: 'ctrl-l' | 'ctrl-alt-l' | 'disabled';
    search: 'ctrl-f' | 'ctrl-alt-f' | 'disabled';
  };
  importShortcut: 'ctrl-i' | 'ctrl-alt-i' | 'disabled';
  aiSummaryShortcut: 'ctrl-enter' | 'ctrl-shift-enter' | 'disabled';
  defaultAiMode: 'local' | 'cloud' | 'mock';
  aiDefaultScope: 'selection' | 'page-lite' | 'page' | 'chapter' | 'volume' | 'book' | 'annotations' | 'library';
  aiNoSelectionFallbackScope: 'page' | 'chapter' | 'book';
  aiCommandDefaultScopes: Record<'summary' | 'characters' | 'foreshadow' | 'timeline' | 'cards', ExtendedSettings['aiDefaultScope']>;
  aiScopePriorityStrategy: 'command-first' | 'panel-first' | 'narrowest-first';
  aiAutoDowngradeScopeOnTokenOverflow: boolean;
  aiScopeTokenLimit: string;
  cloudAiRequestSizeLimitTokens: string;
  aiSlashMenuEnabled: boolean;
  aiBuiltInSlashCommandEnabled: Record<'summary' | 'characters' | 'foreshadow' | 'timeline' | 'cards', boolean>;
  aiDefaultRetrievalStrategy: 'scope-first' | 'entity-extraction' | 'anomaly-extraction' | 'timeline-extraction' | 'key-sentences';
  aiRetrievalQueryRewriteMode: 'off' | 'basic';
  aiMultiStageRetrievalMode: 'off' | 'auto';
  aiCommandRetrievalStrategies: Record<'summary' | 'characters' | 'foreshadow' | 'timeline' | 'cards', ExtendedSettings['aiDefaultRetrievalStrategy']>;
  aiFallbackEnabled: boolean;
  aiFtsUnavailableBehavior: 'show-warning' | 'text-fallback' | 'fail-fast';
  aiLocalIndexResultLimit: string;
  aiCitationMinConfidence: string;
  aiDefaultOutputFormat: 'structured' | 'markdown';
  aiRequireCitations: boolean;
  aiNoCitationWarningEnabled: boolean;
  aiCitationCoverageVisible: boolean;
  aiCitationCardDefaultDensity: 'compact' | 'detailed';
  aiExternalCitationsDisabled: boolean;
  aiCitationJumpRepairEnabled: boolean;
  aiCitationFieldStrictness: 'lenient' | 'normal' | 'strict';
  aiToolCallDisplayMode: 'hidden' | 'summary' | 'full';
  aiRenderedBlockLimit: string;
  aiCustomSlashCommandLimit: string;
  aiRecentSlashCommandLimit: string;
  aiSaveStructuredResponseWithNote: boolean;
  aiCitationDefaultSaveTarget: 'highlight' | 'excerpt' | 'both';
  knowledgeMarkdownExportIncludeAiMetadata: boolean;
  knowledgeMarkdownExportIncludeStructuredResponse: boolean;
  knowledgeMarkdownExportPath: string;
  knowledgeDefaultColumns: Array<'highlights' | 'notes' | 'flashcards'>;
  knowledgeBidirectionalLinksEnabled: boolean;
  knowledgeHighlightCardTemplate: string;
  knowledgeNoteCardTemplate: string;
  knowledgeFlashcardCardTemplate: string;
  highlightFlashcardGenerationEnabled: boolean;
  highlightFlashcardDefaultTags: string;
  highlightFlashcardDefaultReviewStatus: 'new' | 'due' | 'reviewed';
  highlightFlashcardFrontTemplate: string;
  highlightFlashcardBackTemplate: string;
  cloudAiEnabled: boolean;
  localAiEnabled: boolean;
  cloudAiRequireConfirmation: boolean;
  cloudAiAutoRedact: boolean;
  cloudAiSensitiveWords: string;
  cloudAiAllowSelectionText: boolean;
  cloudAiAllowCurrentPageText: boolean;
  cloudAiAllowCurrentChapterText: boolean;
  cloudAiAllowBookSummaryContext: boolean;
  cloudAiRequestHistoryEnabled: boolean;
  cloudAiRequestHistoryLimit: string;
  cloudAiRequestHistorySaveFailed: boolean;
  cloudAiRequestHistorySaveStopped: boolean;
  cloudAiFallbackToLocalOnFailure: boolean;
  aiHybridLocalFirstCloudSummary: boolean;
  aiStreamingFlushIntervalMs: string;
  localAiCancelTimeoutMs: string;
  sidecarEnabled: boolean;
  sidecarCommand: string;
  sidecarWorkingDir: string;
  sidecarHealthTimeoutMs: string;
  sidecarMaxMemoryMb: string;
  experimentalAiToolCallingEnabled: boolean;
  experimentalEpubPdfEnabled: boolean;
  experimentalMultiWindowConflictResolutionEnabled: boolean;
  experimentalKnowledgeGraphEnabled: boolean;
  experimentalSyncEnabled: boolean;
  applicationPrivacyMode: boolean;
  hideRecentReadingInPrivacyMode: boolean;
  hideFilePathsInPrivacyMode: boolean;
  hideBookTitlesInPrivacyMode: boolean;
  appLockEnabled: boolean;
  appLockIdleTimeoutMinutes: string;
  copyDiagnosticsAutoRedact: boolean;
  operationLogRecordInputContent: boolean;
  operationLogRecordPaths: boolean;
  translationFallbackStrategy: 'default-locale' | 'key';
  customTerminologyEnabled: boolean;
  customTerminologyRules: string;
  reduceMotion: boolean;
  highContrast: boolean;
  enhancedFocus: boolean;
  largeTouchTargets: boolean;
  colorBlindFriendlyHighlights: boolean;
  readerReadAloudEnabled: boolean;
  readerReadAloudRate: string;
  readerReadAloudPitch: string;
  readerReadAloudNarratorVoiceURI: string;
  readerReadAloudMaleVoiceURI: string;
  readerReadAloudFemaleVoiceURI: string;
  readerReadAloudCharacterVoiceRules: string;
  moyuReaderProfile: MoyuReaderProfile;
  defaultViewMode: 'card' | 'list' | 'shelf';
  defaultSort: 'recent' | 'title' | 'progress' | 'trashExpiry';
  defaultFilter: 'all' | 'unread' | 'reading' | 'done';
  duplicateStrategy: 'skip' | 'replace' | 'copy' | 'ask';
  defaultCoverToneStrategy: 'format' | 'hash' | 'progress';
  defaultCoverLabelStrategy: 'format' | 'ai' | 'read' | 'knowledge' | 'first-char';
  cleanTitleFromFilename: boolean;
  autoDetectAuthor: boolean;
  defaultImportPath: string;
  importFileFilter: 'txt' | 'all';
  txtImportEncodingMode: 'auto' | 'utf-8' | 'gb18030';
  openImportedBookAfterImport: boolean;
  directoryImportRecursive: boolean;
  showImportSummaryAfterImport: boolean;
  continueDirectoryImportAfterFailure: boolean;
  autoCleanTxtOnImport: boolean;
  autoParseTocOnImport: boolean;
  autoRebuildTocWhenEmpty: boolean;
  tocRuleChangeRebuildMode: 'off' | 'prompt' | 'auto';
  previewTocRebuildDiff: boolean;
  autoBackupImportedOriginals: boolean;
  confirmMoveToTrash: boolean;
  confirmPermanentDelete: boolean;
  confirmEmptyTrash: boolean;
  showEmptyLibraryGuide: boolean;
  rememberLibraryTabState: boolean;
  showLibraryDetailSidebar: boolean;
  libraryDensity: 'compact' | 'comfortable' | 'spacious';
  searchScope: 'page' | 'chapter' | 'book' | 'annotations' | 'bookmarks' | 'all';
  searchLimit: string;
  globalSearchMode: 'instant' | 'enter';
  globalSearchDebounceMs: string;
  globalSearchSnippetLength: string;
  globalSearchShowScore: boolean;
  globalSearchHistoryLimit: string;
  globalSearchSavedLimit: string;
  caseSensitive: boolean;
  fuzzy: boolean;
  regex: boolean;
  readerSearchRegexFallbackLiteral: boolean;
  searchNormalizeTraditionalChinese: boolean;
  searchNormalizeNfkc: boolean;
  searchPinyinInitials: boolean;
  autoIndexImportedBooks: boolean;
  indexStrategyVersion: 'stable' | 'latest' | 'compat';
  indexChunkSize: string;
  indexChunkOverlap: string;
  indexRebuildStrategy: 'manual' | 'prompt' | 'auto';
  ftsRepairStrategy: 'manual' | 'prompt' | 'auto';
  indexRecentErrorLimit: string;
  indexPauseResumeStrategy: 'manual' | 'ask' | 'auto';
  readerSearchHistoryLimit: string;
  readerSavedSearchLimit: string;
  readerSearchChapterFilterDefault: 'all' | 'current';
  readerSearchHighlightColor: 'amber' | 'blue' | 'green' | 'pink' | 'violet' | 'red';
  defaultHighlightColor: 'yellow' | 'green' | 'blue' | 'pink' | 'violet' | 'red';
  highlightColorShortcuts: Record<ExtendedSettings['defaultHighlightColor'], '1' | '2' | '3' | '4' | '5' | '6' | 'disabled'>;
  highlightColorMeanings: Record<ExtendedSettings['defaultHighlightColor'], string>;
  defaultHighlightImportance: 'normal' | 'high' | 'critical';
  defaultHighlightReviewStatus: 'new' | 'due' | 'reviewed';
  highlightOverlapStrategy: 'first-start-longest' | 'latest-created' | 'highest-importance';
  anchorRepairStrategy: 'context-first' | 'text-first' | 'manual';
  defaultExportFormat: 'markdown' | 'csv' | 'anki' | 'obsidian' | 'logseq' | 'readwise' | 'json';
  annotationExportContent: 'highlights' | 'bookmarks' | 'notes' | 'all';
  annotationJsonImportConflictStrategy: 'skip' | 'overwrite' | 'merge';
  annotationMarkdownTemplate: string;
  annotationExportLastDirectory: string;
  annotationCsvFields: Array<'type' | 'id' | 'chapter' | 'text' | 'note' | 'color' | 'createdAt' | 'location'>;
  ankiDefaultTags: string;
  obsidianWikiLinks: boolean;
  logseqPropertyFormat: boolean;
  readwiseDefaultAuthor: string;
  annotationTagSuggestionsEnabled: boolean;
  annotationMarkdownEditorEnabled: boolean;
  selectionMenuEnabled: boolean;
  doubleClickWordSelectionEnabled: boolean;
  contextMenuEnabled: boolean;
  openNoteAfterHighlight: boolean;
  allowEmptyNotes: boolean;
  noteDefaultSaveTarget: 'knowledge' | 'book' | 'inbox';
  noteAutoReaderLocation: boolean;
  noteAutoContext: boolean;
  noteTemplate: string;
  defaultBookmarkSort: 'created-desc' | 'created-asc' | 'chapter-asc';
  defaultBookmarkGroupBy: 'none' | 'chapter' | 'created' | 'tag';
  defaultBookmarkTags: string;
  defaultBookmarkColor: 'yellow' | 'green' | 'blue' | 'pink' | 'violet' | 'red';
  bookmarkTitleFromChapter: boolean;
  arrowKeyPaging: boolean;
  spaceKeyPaging: boolean;
  escapeClosesPanels: boolean;
  homeEndJump: boolean;
  vimStyleNavigation: boolean;
  readerShortcuts: {
    highlight: 'h' | 'ctrl-h' | 'disabled';
    bookmark: 'm' | 'ctrl-m' | 'disabled';
    aiPanel: 'a' | 'ctrl-alt-a' | 'disabled';
    search: 'ctrl-f' | 'slash' | 'disabled';
  };
  pageClickPaging: boolean;
  gesturePagingEnabled: boolean;
  gesturePagingThresholdPx: string;
  autoHideCursor: boolean;
  pageTurnSound: boolean;
  chapterNoticeDurationMs: string;
  virtualChapterRadius: string;
  virtualParagraphWindowSize: string;
  wheelPagingThresholdPx: string;
  autoSaveReaderPosition: boolean;
  readerPositionSaveDebounceMs: string;
  multiWindowReaderSync: boolean;
  booksOpenInStandaloneReader: boolean;
  readerNavHiddenByStandaloneOnly: boolean;
  multiWindowConflictStrategy: 'latest' | 'current-window' | 'manual';
  readerProgressMode: 'chapters' | 'characters' | 'pages';
  tocShowVolumeHierarchy: boolean;
  tocVolumeClickable: boolean;
  tocShowChapterNumbers: boolean;
  tocCollapseVolumes: boolean;
  tocExpandActiveVolume: boolean;
  tocShowChapterWordCount: boolean;
  tocShowChapterProgress: boolean;
  tocTitleGroupingEnabled: boolean;
  tocTitleGroupKeywords: string;
  tocTitleGroupRules: TocTitleGroupRuleDraft[];
  tocAllowRename: boolean;
  tocAllowHide: boolean;
  tocAllowUnhide: boolean;
  tocAllowSplit: boolean;
  tocAllowMergeNext: boolean;
  tocAllowRestoreDefault: boolean;
  tocAllowUndoRedo: boolean;
  readerHistoryStackLimit: string;
  readerDailyGoalEnabled: boolean;
  readerDailyPagesGoal: string;
  readerDailyMinutesGoal: string;
  readerDailyChaptersGoal: string;
  recordRecentReaderBooks: boolean;
  trackReadingTime: boolean;
  largeBookPerformanceMode: boolean;
  readerPageCacheEnabled: boolean;
  readerPagePreheatEnabled: boolean;
  readerPageMeasureCacheLimit: string;
  readerFpsDiagnosticsEnabled: boolean;
  readerMemoryWarningEnabled: boolean;
  readerMemoryWarningThresholdMb: string;
  readerPageCacheLimit: string;
  readerPagePreheatRange: string;
  taskConcurrency: string;
  importConcurrency: string;
  parseConcurrency: string;
  ftsWriteSerial: boolean;
  vectorConcurrencyReserved: string;
  taskRetryCount: string;
  operationLogRetention: string;
  taskLogRetention: 'session' | '7-days' | '30-days' | '90-days' | 'forever';
  completedTaskRetentionLimit: string;
  dataAutoBackupEnabled: boolean;
  dataAutoBackupFrequency: 'daily' | 'weekly' | 'monthly';
  dataAutoBackupRetentionLimit: string;
  dataBackupMode: 'full' | 'incremental';
};

export type ChapterRegexRuleDraft = {
  id: string;
  name: string;
  pattern: string;
  enabled: boolean;
  priority: number;
};

export type TocTitleGroupRuleDraft = {
  id: string;
  name: string;
  groupName: string;
  pattern: string;
  enabled: boolean;
  priority: number;
};

export type CustomCleanupRuleDraft = {
  id: string;
  name: string;
  pattern: string;
  replacement: string;
  enabled: boolean;
  mode: 'remove-line' | 'replace';
  priority: number;
};

export type ChapterRuleDraft = {
  enabled: boolean;
  tocHierarchyMode: 'novel' | 'document';
  maxHeadingLength: number;
  minHeadingConfidence: number;
  enableChineseChapter: boolean;
  enableChineseVolume: boolean;
  enableSpecialHeadings: boolean;
  enableEnglishChapter: boolean;
  enableCompactSplit: boolean;
  compactHeadingSuffixLength: number;
  preserveCompactPrefixText: boolean;
  autoDetectBookTitle: boolean;
  bookTitleBracketMode: 'book-title' | 'angle' | 'both' | 'custom';
  customBookTitleBracketPattern: string;
  bookTitleMaxLength: number;
  firstLineAsBookTitle: boolean;
  inferBookTitleFromFileName: boolean;
  paragraphMode: 'line' | 'blank-line' | 'merge-short-lines' | 'chinese-reflow';
  shortLineMergeThreshold: number;
  longParagraphSliceSize: number;
  autoIgnoreAdHeadings: boolean;
  autoIgnoreRepeatedTocHeadings: boolean;
  removeAds: boolean;
  adKeywords: string;
  removeAdUrls: boolean;
  removePaginationNoise: boolean;
  preserveOriginalBackup: boolean;
  normalizeBlankLines: boolean;
  trimTrailingWhitespace: boolean;
  normalizeFullWidthSpaces: boolean;
  customCleanupRules: CustomCleanupRuleDraft[];
  forbiddenHeadingPunctuation: string;
  forbiddenHeadingStartChars: string;
  customRegexRules: ChapterRegexRuleDraft[];
  customRegex: string;
};

export type AiCustomSlashCommandDraft = {
  id: `custom-${string}`;
  label: string;
  prompt: string;
  aliases: string[];
  scopeHint: ExtendedSettings['aiDefaultScope'];
  outputHint: string;
  retrievalStrategy: 'scope-first';
};

export type SettingsChangeHistoryEntry = {
  id: string;
  changedAt: string;
  scope: SettingsUpdatedDetail['scope'];
  key: string;
  keys: string[];
  summary: string;
  previousExtendedSettings?: ExtendedSettings;
};

export type SettingsUpdatedDetail = {
  key?: string;
  keys?: string[];
  scope?: 'app' | 'extended' | 'reader' | 'chapterRules' | 'all';
  extended?: ExtendedSettings;
  localePreference?: 'system' | 'zh-CN' | 'en-US' | 'ja-JP' | 'es-ES' | 'fr-FR' | 'ko-KR';
};

export type SettingsV2 = {
  settingsSchemaVersion: number;
  global: Record<string, unknown>;
  reader: Record<string, unknown>;
  extended: Partial<ExtendedSettings>;
};

export type DataDirectoryStatus = {
  dataDir: string;
  defaultDataDir: string;
  mode: 'default' | 'custom' | 'portable' | string;
  locatorFile: string;
  portableDir: string;
  customDataDir: string;
  exists: boolean;
  portableAvailable: boolean;
};

export type DataDirectoryMigrationProgress = {
  phase: 'preparing' | 'copying' | 'rewriting' | 'finalizing' | 'cleaning' | 'completed' | string;
  copiedFiles: number;
  totalFiles: number;
  copiedBytes: number;
  totalBytes: number;
  currentPath: string;
};
